### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2

### ISSUE THREAD

**Issue by Iamno0b** [wangshub/wechat_jump_game#1124]
请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？ y/n [y]: y
程序版本号：1.1.1
Traceback (most recent call last):
  File "one_step_auto_beta1.py", line 268, in <module>
  File "one_step_auto_beta1.py", line 238, in main
  File "common\debug.py", line 51, in dump_device_info
    device_str = os.popen('adb shell getprop ro.product.model').read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2: illegal multibyte sequence
[11308] Failed to execute script one_step_auto_beta1

我是小白，不知道怎么处理这问题

**Comment by leon332157** [comment]
你在文件开头加上：
# coding=utf8
试试，可能这不是gbk编码

**Comment by leon332157** [comment]
#coding=utf8
忘记md语法了😓
