### ISSUE TITLE
未能运行脚本

### ISSUE THREAD

**Issue by chenfengfeng** [wangshub/wechat_jump_game#1131]
程序版本号：2018年01月18日clone 的库
**********
Screen: Physical size: 5.5
Density: Physical density: x
Override density: x
Device: iPhone 7 plus
Phone OS: 11.2.2
Host OS: x
Python: 3.6
**********

遇到问题：

运行http://localhost:8100/status
```
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "11.2.2"
    },
    "ios" : {
      "simulatorVersion" : "11.2.2",
      "ip" : "192.168.31.71"
    },
    "build" : {
      "time" : "Jan 18 2018 09:54:42"
    }
  },
  "sessionId" : "3CCA8B1B-890A-4C88-9074-ADE0762B8327",
  "status" : 0
}
```

运行http://localhost:8100/inspector
![](https://user-images.githubusercontent.com/6957977/35078581-de9c7bae-fc3d-11e7-828b-21fe774c8790.jpg)

运行iproxy 8100 8100
```
chenzefengdeiMac:~ fengfeng$ iproxy 8100 8100
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 3
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 6
waiting for connection
Number of available devices == 3
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
accepted connection, fd = 4
waiting for connection
Number of available devices == 3
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
accepted connection, fd = 4
waiting for connection
Number of available devices == 3
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 6
waiting for connection
Number of available devices == 3
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
accepted connection, fd = 4
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 6
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 6
run_stoc_loop: fd = 6
accepted connection, fd = 8
waiting for connection
Number of available devices == 2
Requesting connecion to device handle == 25 (serial: 94bcf24c3144e3310a250beca93505086bf4ca2d), port 8100
run_ctos_loop: fd = 8
run_stoc_loop: fd = 8
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
recv failed: Resource temporarily unavailable
recv failed: Operation not permitted
```

执行wechat_jump_auto_iOS.py错误
```
chenzefengdeiMac:wechat_jump_game fengfeng$ python3 wechat_jump_auto_iOS.py
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 51, in <module>
    s = c.session()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 77, in httpdo
    retjson = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

目前的问题是不能运行脚本,不知道是 python 的关系还是什么原因
已经查看了其他的 issues, 虽然有一样的问题,但不能解决我的问题
有么有大佬能帮我下~不胜感激~

改进和建议：无

**Comment by leon332157** [comment]
会不会是权限问题，用sudo或者管理员权限试试？

**Comment by leon332157** [comment]
报错信息有opration not permitted

**Comment by chenfengfeng** [comment]
@leon332157 感谢~真的是权限问题- -
如果其他人遇到我这种情况.可以试试
sudo python3 wechat_jump_iOS_py3.py

**Comment by CrabMen** [comment]
@chenfengfeng @leon332157 我使用sudo之行以后依旧是没有反应 ，情况跟你的类似，问题描述在#1166里面，大佬，能帮忙看一下么
