### ISSUE TITLE
截图用adb工具截下来了，然后也上传了，但是运行出现这个问题，是啥原因

### ISSUE THREAD

**Issue by 1programmer2dfg3** [wangshub/wechat_jump_game#128]
这是报错日志：
Traceback (most recent call last):
  File "E:\WeCharGamePython\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 95, in <module>
    main()
  File "E:\WeCharGamePython\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 84, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by wangshub** [comment]
能找到 '1.png'图片吗 @1programmer2dfg3

**Comment by ShiftCtrlAlt** [comment]
+1

**Comment by mjzcyhp** [comment]
@wangshub 我的运行python wichat_jump_jsfjajf.py，后就跳出一张图片，然后就卡住了，怎么解决啊

**Comment by Jasper2018** [comment]
我的是anoconda下的Spyder，屏幕闪了好几下，也是这个错误

**Comment by Jasper2018** [comment]
是需要开启华为手机的什么吗，我已经开启了USB调试了

**Comment by lovebluedan** [comment]
这个会不会是因为文件的编码问题

**Comment by aixuyi** [comment]
我也是这个，找不到1.png'图片

**Comment by lovebluedan** [comment]
你们有没有在这项目的目录下上传图片？
