### ISSUE TITLE
ioError   No such file or directory: './1.png'

### ISSUE THREAD

**Issue by ShiftCtrlAlt** [wangshub/wechat_jump_game#132]
error: device offline
error: device offline
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 153, in <module>
    main()
  File "wechat_jump_auto.py", line 141, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by Chen-Sanjia** [comment]
设备离线，重新插一下，开调试模式

**Comment by ShiftCtrlAlt** [comment]
@Chen-Sanjia 无语了，搞了半天一直都是设备离线。手机助手连接又可以

**Comment by ShiftCtrlAlt** [comment]
@Chen-Sanjia 我找到原因了，adb版本过低，导致4.2以上的android一直都是离线的。我用SDK Manager升级了下就可以了。
