### ISSUE TITLE
Error opening file: /sdcard/test.png (Permission denied)  什么情况，捂脸

### ISSUE THREAD

**Issue by 985211yygg** [wangshub/wechat_jump_game#170]
H:\python\workspace\spider163\venv\Scripts\python.exe I:/wechat_jump_game-master/wechat_jump_auto.py
Error opening file: /sdcard/test.png (Permission denied)
remote object '/sdcard/test.png' does not exist
Traceback (most recent call last):
  File "I:/wechat_jump_game-master/wechat_jump_auto.py", line 169, in <module>
    main()
  File "I:/wechat_jump_game-master/wechat_jump_auto.py", line 156, in main
    im = Image.open("./test.png")
  File "H:\python\workspace\spider163\venv\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './test.png'

Process finished with exit code 1

**Comment by SbyXlmm** [comment]
adb没整好。权限不够。

**Comment by 985211yygg** [comment]
@SbyXlmm 问题是我的android studio截图录屏什么的都很正常啊
