### ISSUE TITLE
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2530, in open     fp = builtins.open(filename, "rb") IOError: [Errno 2] No such file or directory: './1.png'

### ISSUE THREAD

**Issue by dchaofei** [wangshub/wechat_jump_game#174]
```
minLayer = 0, maxLayer = 4294967295
capture ok : w = 1080, h = 1920, s = 1088, f = 1, size = 8355840
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 177, in <module>
    main()
  File "wechat_jump_auto.py", line 164, in main
    im = Image.open("./1.png")
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'
```
看手机上有截图的，没用过 python 很懵逼，说是找不到这个文件夹。。

**Comment by sunguoan04** [comment]
我的也是这个问题，win10

**Comment by NapleC** [comment]
同问，没用过python表示一脸懵逼

**Comment by KooSung** [comment]
同样的问题，求解决办法

**Comment by dchaofei** [comment]
@sunguoan04 发现不是系统的问题，是设备的事，出问题的是锤子 M1，换个小米的可以用了。

**Comment by F-loat** [comment]
新版本应该没这个问题了 #288
