### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by sunguoan04** [wangshub/wechat_jump_game#176]
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\sungu\Desktop\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py 

Traceback (most recent call last):
  File "C:\Users\sungu\Desktop\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 176, in <module>
    main()
  File "C:\Users\sungu\Desktop\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 163, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'
>>>

**Comment by sunguoan04** [comment]
问题已解决，需要把adb复制到项目根目录下
