### ISSUE TITLE
老铁们,这个是什么问题?

### ISSUE THREAD

**Issue by petteran** [wangshub/wechat_jump_game#193]
```
1394 KB/s (46088 bytes in 0.032s)
Traceback (most recent call last):
  File "C:/Disk/Desktop/wechat_jump_game-master/wechat.py", line 34, in <module>
    im = plt.imshow(img, animated=True)
  File "C:\Python27\lib\site-packages\matplotlib\pyplot.py", line 3101, in imshow
    **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "C:\Python27\lib\site-packages\matplotlib\axes\_axes.py", line 5127, in imshow
    im.set_data(X)
  File "C:\Python27\lib\site-packages\matplotlib\image.py", line 607, in set_data
    raise TypeError("Image data cannot be converted to float")
TypeError: Image data cannot be converted to float
```

**Comment by wangshub** [comment]
你是py2.7，现在已经升级成py3了，看下是不是这个原因 @petteran

**Comment by chenjiandongx** [comment]
请使用最新版本的代码
