### ISSUE TITLE
运行出现错误 帮我看看吧

### ISSUE THREAD

**Issue by ccldvv** [wangshub/wechat_jump_game#204]
========== RESTART: C:\wechat_jump_game-master\wechat_jump_auto.py ==========

Traceback (most recent call last):
  File "C:\wechat_jump_game-master\wechat_jump_auto.py", line 161, in <module>
    main()
  File "C:\wechat_jump_game-master\wechat_jump_auto.py", line 148, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'
>>>

**Comment by mjzcyhp** [comment]
config.json这个文件你引入了没有啊

**Comment by lly2016** [comment]
把代码运行的路径添加到环境变量里面，或者加一句os.chdir

**Comment by ccldvv** [comment]
@mjzcyhp  怎么引入。

**Comment by lly2016** [comment]
你这个不是json的问题，加一句os.chdir就行了

**Comment by ccldvv** [comment]
@lly2016   谢谢大佬 已经OK了
