### ISSUE TITLE
代码操作，环境搭建问题，请反馈到这里

### ISSUE THREAD

**Issue by wangshub** [wangshub/wechat_jump_game#217]

**Comment by Billiuhp** [comment]
Load default config
Traceback (most recent call last):
  File "Wechat_jump_auto.py", line 66, in <module>
    is_debug = config['debug']
KeyError: 'debug'

**Comment by doubiermie** [comment]
C:\Users\Yangzichen\Desktop\123\wechat_jump_game-master>python wechat_jump_auto.py
Load config file from ./config/1920x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 62, in <module>
    is_debug = config['debug']
KeyError: 'debug'

**Comment by wangshub** [comment]
请更新一下代码 @doubiermie

**Comment by wangshub** [comment]
ADB 安装和使用，可以参考一下
https://github.com/wangshub/wechat_jump_game/issues/194

**Comment by kaizhetutuquliaomei** [comment]
iOS的一直卡在这里：
python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 29, in <module>
    pull_screenshot()
  File "wechat_jump_iOS_py3.py", line 18, in pull_screenshot
    c.screenshot('1.png')
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

**Comment by jacentsao** [comment]
请教一下这个怎么处理，已经能够访问localhost:8100/status 了，但是运行脚本就报错 iOS
```
python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 15, in <module>
    s = c.session()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 77, in httpdo
    retjson = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Elvis23** [comment]
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 195, in from_line
    if (os.path.isdir(p) and
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/genericpath.py", line 42, in isdir
    st = os.stat(s)
ValueError: embedded null byte
下载项目配置文件一直卡在这里请问是什么原因呢

**Comment by ihewro** [comment]
楼上 +1 ，不知道具体python 3什么版本的？

pip版本：

pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)

Python 3.6.4

**Comment by MooYoo** [comment]
运行提示sudo python3 wechat_jump_iOS_py3.py

Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'

-----------------------------------------------------------
Mac，访问http://127.0.0.1:8100/status可以得到返回数据：

{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "11.2.1"
    },
    "ios" : {
      "simulatorVersion" : "11.2.1",
      "ip" : null
    },
    "build" : {
      "time" : "Dec 31 2017 19:51:15"
    }
  },
  "sessionId" : "CCACB740-723F-4E06-95AE-00C96F003C2D",
  "status" : 0
}


Xcode也运行项目正常~打印如下：

2017-12-31 21:40:45.786082+0800 WebDriverAgentRunner-Runner[2113:494458] +[CATransaction synchronize] called within transaction
2017-12-31 21:40:46.156610+0800 WebDriverAgentRunner-Runner[2113:494458] Running tests...
2017-12-31 21:40:50.157362+0800 WebDriverAgentRunner-Runner[2113:494458] Continuing to run tests in the background with task ID 1
Test Suite 'All tests' started at 2017-12-31 21:40:51.738
Test Suite 'WebDriverAgentRunner.xctest' started at 2017-12-31 21:40:51.743
Test Suite 'UITestingUITests' started at 2017-12-31 21:40:51.743
Test Case '-[UITestingUITests testRunner]' started.
    t =     0.01s Start Test at 2017-12-31 21:40:51.750
    t =     0.01s Set Up
2017-12-31 21:40:51.833797+0800 WebDriverAgentRunner-Runner[2113:494458] Built at Dec 31 2017 19:51:13
2017-12-31 21:40:51.958158+0800 WebDriverAgentRunner-Runner[2113:494458] ServerURLHere->http://localhost:8100<-ServerURLHere

**Comment by LIHAOCHI** [comment]
报错
`Traceback (most recent call last):
  File "E:\wechat\wechat_jump_auto.py", line 57, in <module>
    config = open_accordant_config()
  File "E:\wechat\wechat_jump_auto.py", line 43, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\wechat/config/default.json'`

**Comment by LIHAOCHI** [comment]
报错
Traceback (most recent call last):
  File "E:\wechat\wechat_jump_auto.py", line 57, in <module>
    config = open_accordant_config()
  File "E:\wechat\wechat_jump_auto.py", line 43, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\wechat/config/default.json'

**Comment by LingyvKong** [comment]
报错
File "common\config.py", line 25, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:

IOError: [Errno 2] No such file or directory: '/config/default.json'
找不到这个文件？为什么会这样

**Comment by fyk941127** [comment]
Traceback (most recent call last):
  File "F:\python\youjumpijump-1.15\wechat_jump_game-master\wechat_jump_auto.py"
, line 34, in <module>
    config = config.open_accordant_config()
  File "F:\python\youjumpijump-1.15\wechat_jump_game-master\common\config.py", l
ine 15, in open_accordant_config
    screen_size = _get_screen_size()
  File "F:\python\youjumpijump-1.15\wechat_jump_game-master\common\config.py", l
ine 34, in _get_screen_size
    size_str = os.popen('adb shell wm size').read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\os.
py", line 980, in popen
    bufsize=buffering)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sub
process.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sub
process.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

为啥会运行这个错误

**Comment by hazier** [comment]
运行之后出现Figure 1一张截图出现后不跳 命令行窗口中显示如下：

10 KB/s (30812 bytes in 3.008s)
254 KB/s (30812 bytes in 0.118s)
now =  [(480.71212121212136, 603.482683982684)]
now =  [(709.2835497835498, 1005.2142857142857)]
distance =  462.2046925216379
adb shell input swipe 320 410 320 410 623
Error: Invalid arguments for command: swipe
usage: input ...
       input text <string>
       input keyevent <key code number or name>
       input [touchscreen|touchpad|touchnavigation] tap <x> <y>
       input [touchscreen|touchpad|touchnavigation] swipe <x1> <y1> <x2> <y2> [duration(ms)]
       input trackball press
       input trackball roll <dx> <dy>
       input rotationevent <rotation_code:0->0 1->90 2->180 3->270>
233 KB/s (30812 bytes in 0.129s)

===========================================================
请问那个error该怎么解决？

**Comment by dujinyu** [comment]
pip install -r C:\Users\Administrator\Desktop\requirements.txt的时候出现错误Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-yfyfs8ff\matplotlib\表示不太懂，
还出现
C:\Users\Administrator>python G:\wechat_jump_auto.py
Traceback (most recent call last):
  File "G:\wechat_jump_auto.py", line 24, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'，安装pil的时候找不到，安装替代的pillow也出现一堆问题
