### ISSUE TITLE
我这种情况是不是adb没装啊

### ISSUE THREAD

**Issue by akuan1993** [wangshub/wechat_jump_game#221]
Traceback (most recent call last):
  File "C:\Users\MNCM\Desktop\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 100, in <module>
    main()
  File "C:\Users\MNCM\Desktop\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 89, in main
    im = Image.open("./1.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by wangshub** [comment]
https://github.com/wangshub/wechat_jump_game/issues/194
