### ISSUE TITLE
安装依赖异常 

### ISSUE THREAD

**Issue by susanso1988** [wangshub/wechat_jump_game#237]
我已经设置好adb环境变量了。接着我在cmd 切换到根目录中 pip install -r requirements.txt然后就出现以下错误。。

Exception:
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "D:\Python27\lib\site-packages\pip\commands\install.py", line 262, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "D:\Python27\lib\site-packages\pip\req.py", line 1631, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "D:\Python27\lib\site-packages\pip\req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "D:\Python27\lib\site-packages\pip\req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "D:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "D:\Python27\lib\site-packages\pip\_vendor\pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', '\xff\xfeb\x00a\x00c\x00k\x00p\x00o\x00r\x00t\x00s\x00.\x00f\x00u\x00n\x00c\x00t\x00o\x00o\x00l\x00s\x00-\x00l\x00r\x00u\x00-\x00c\x00a\x00c\x00h\x00e\x00=\x00=\x001\x00.\x004\x00')

Storing debug log for failure in C:\Users\root\pip\pip.log

**Comment by wangshub** [comment]
这个不太属于bug问题，需要自己先谷歌一下哦 @susanso1988
