### ISSUE TITLE
iOS脚本运行报错，能够正常访问到localhost:8100/status 

### ISSUE THREAD

**Issue by jacentsao** [wangshub/wechat_jump_game#255]
```
请教一下这个怎么处理，已经能够访问localhost:8100/status 了，但是运行脚本就报错 iOS

python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 15, in <module>
    s = c.session()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 77, in httpdo
    retjson = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by wangshub** [comment]
https://github.com/wangshub/wechat_jump_game/issues/99
@jacentsao 参考这个

**Comment by yahoouchen** [comment]
@jacentsao 上面的问题你是怎么解决的？

**Comment by jacentsao** [comment]
@yahoouchen 没搞定，不知道什么问题，没玩了

**Comment by wangjinbo1** [comment]
@jacentsao 你解决了吗，怎么解决的
