### ISSUE TITLE
wechat_jump_auto_1280_720 windows无法运行

### ISSUE THREAD

**Issue by 0312birdzhang** [wangshub/wechat_jump_game#256]
@Phoobobo 
错误如下：
```
cannot create 'original_screen_shots\': Not a directory
Traceback (most recent call last):
  File "d:/code/wechat_jump_game/wechat_jump_auto_1280_720.py", line 164, in <module>
    main()
  File "d:/code/wechat_jump_game/wechat_jump_auto_1280_720.py", line 150, in main
    im = Image.open("{}{}{}.png".format(origin_dir, img_ext, i))
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'original_screen_shots/screen1.png'
PS D:\code\wechat_jump_game>
```
第56行修改为`os.system('adb pull {} {}.'.format(img_path, origin_dir))`可以运行

**Comment by Phoobobo** [comment]
出现这种错误往往是手机里有重名文件导致的，改一下img_path就行了

**Comment by 0312birdzhang** [comment]
我把adb pull的命令改为`adb pull xxx xxx/.`就可以了

**Comment by ObjLin** [comment]
跑了400多 就不动了

**Comment by Phoobobo** [comment]
横坐标看看输出的有辅助线的图片，跳跃路径终点的横向坐标对不对，不对就是算法还不够完美。我最多跑到8650，少的时候也就几百，有时候还是靠运气哈哈。大家找找原因，把算法看能不能做到完美
