### ISSUE TITLE
[Errno 2] No such file or directory: '1.png'

### ISSUE THREAD

**Issue by shizhidi** [wangshub/wechat_jump_game#28]
C:\Users\Administrator\AppData\Local\Programs\Python\Python36\python.exe D:/work/wechat_jump_game/wechat_jump_py3.py
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
'adb' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Traceback (most recent call last):
  File "D:/work/wechat_jump_game/wechat_jump_py3.py", line 25, in <module>
    img = np.array(Image.open('1.png'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '1.png'

**Comment by Mupceet** [comment]
需要本地新建 screenshot_backups 文件夹。

**Comment by MovvoM** [comment]
乱码是英文吗？我觉得是缺少adb工具包，然后无法截图并pull到电脑上，导致错误。可以下载啊adb工具包，并添加到环境变量里

**Comment by MovvoM** [comment]
说错了，乱码是中文吗

**Comment by wangshub** [comment]
更新了检测screenshot_backups文件路径代码 @Mupceet @MovvoM

**Comment by MovvoM** [comment]
@wangshub 哦哦，我昨天下载的代码不需要哎

**Comment by shizhidi** [comment]
![image](https://user-images.githubusercontent.com/7605007/34450722-3a162bde-ed4c-11e7-875c-c3ceac7fec9a.png)

**Comment by wangshub** [comment]
可以试着点两下就知道啦 @shizhidi

**Comment by caistrong** [comment]
Traceback (most recent call last):
  File "D:\caistrong\wechat_jump_game\wechat_jump_auto.py", line 126, in <module>
    main()
  File "D:\caistrong\wechat_jump_game\wechat_jump_auto.py", line 115, in main
    im = Image.open("./1.png")
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by caistrong** [comment]
同样的问题

**Comment by Mebigger** [comment]
@caistrong 我的也是，在windows powershell运行就可以，但是分数不高

**Comment by SimonHe96** [comment]
求助，运行adb shell screencap -p /sdcard/1.png， 报error: device not found的错误。
