### ISSUE TITLE
pip install image失败

### ISSUE THREAD

**Issue by livathon** [wangshub/wechat_jump_game#306]
pip install -r requirements.txt已成功执行，当执行到
pip install image一步时失败，如下，麻烦大神帮忙看下
E:\WorkRelated\Wechat_Jump\wechat_jump_game-master>pip install image
Collecting image
  Using cached image-1.5.17-py2.py3-none-any.whl
Requirement already satisfied: pillow in d:\programdata\python27\lib\site-packages (from image)
Collecting django (from image)
  Using cached Django-2.0.tar.gz
Exception:
Traceback (most recent call last):
  File "d:\programdata\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "d:\programdata\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "d:\programdata\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "d:\programdata\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "d:\programdata\python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "d:\programdata\python27\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "d:\programdata\python27\lib\site-packages\pip\utils\__init__.py", line 605, in unpack_file
    untar_file(filename, location)
  File "d:\programdata\python27\lib\site-packages\pip\utils\__init__.py", line 577, in untar_file
    with open(path, 'wb') as destfp:
IOError: [Errno 22] invalid mode ('wb') or filename: 'c:\\users\\livathon\\appdata\\local\\temp\\pip-build-cicivy\\django\\tests/staticfiles_tests/apps/test/static/test/\xe2\x8a\x97.txt'

**Comment by livathon** [comment]
已搞定，版本不对，python安装的是2.7，而执行安装image会自动默认安装Django2.0，而该玩意儿依赖py3，所以报错，解决方法：安装image之前先手动安装Django，即执行命令：pip install Django==1.10.8
