### ISSUE TITLE
OError: cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by gavinYip** [wangshub/wechat_jump_game#321]
Load config file from ./config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
=====           
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 3
=====

Traceback (most recent call last):
  File "D:\game\jumpgame\wechat_jump_game-master\wechat_jump_auto.py", line 231, in <module>
    main()
  File "D:\game\jumpgame\wechat_jump_game-master\wechat_jump_auto.py", line 218, in main
    im = Image.open("./autojump.png")
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2274, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by wangzihan424** [comment]
将pull_screenshot改为下面这样。
os.system('adb shell screencap -p /sdcard/autojump.png')
os.system('adb pull /sdcard/autojump.png .')

**Comment by qitianjin** [comment]
这个错误是因为adb安装的问题还是怎样？其它都能运行只有auto出现这个问题？找不到路径的原因是？
