### ISSUE TITLE
pip install -r requirements.txt 报错 

### ISSUE THREAD

**Issue by ronanhardiman** [wangshub/wechat_jump_game#332]
pip install -r requirements.txt 后报错，
`pip install -r requirements2.txt
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 195, in from_line
    if (os.path.isdir(p) and
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: stat() argument 1 must be encoded string without null bytes, not unicode`

mac 环境
网上找了找，没解决问题，
谢谢。

**Comment by chenjialin** [comment]
环境：
ubuntu 17.04
python3.5
pip install -r requirements.txt 后报错：
Exception:
Traceback (most recent call last):
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/commands/install.py", line 330, in run
    wheel_cache
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/req/req_file.py", line 158, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/home/jedrek/py3env/lib/python3.5/site-packages/pip/req/req_install.py", line 195, in from_line
    if (os.path.isdir(p) and
  File "/home/jedrek/py3env/lib/python3.5/genericpath.py", line 42, in isdir
    st = os.stat(s)
ValueError: embedded null byte

**Comment by chenjialin** [comment]
@ronanhardiman requirements.txt的编码有问题， 修改后就可以了

**Comment by ZackZheng2014** [comment]
[requirements.txt](https://github.com/wangshub/wechat_jump_game/files/1595266/requirements.txt)

@ronanhardiman Mac用这个文件，转好了，实测可用。

**Comment by Vg1ee** [comment]
@ronanhardiman 我也遇到了相同的问题，你解决了吗？

**Comment by ianly** [comment]
requirements.txt 这个文件编码问题，改成 utf-8，或者你新建一个记事本，重写一下

**Comment by ronanhardiman** [comment]
@chenjialin @ianly  谢谢，是这个原因。
@Vg1ee 可以试试。
