### ISSUE TITLE
报错Traceback (most recent call last):   File "C:\Users\szh\Desktop\wechat_jump_auto.py", line 57, in <module>     config = open_accordant_config()   File "C:\Users\szh\Desktop\wechat_jump_auto.py", line 43, in open_accordant_config     with open('{}/config/default.json'.format(sys.path[0]), 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\szh\\Desktop/config/default.json'

### ISSUE THREAD

**Issue by shenzhenhan** [wangshub/wechat_jump_game#333]

**Comment by shenzhenhan** [comment]
谢谢大佬们

**Comment by nanyang24** [comment]
@shenzhenhan 是什么原因呢

**Comment by imappalled** [comment]
解决了吗

**Comment by shenzhenhan** [comment]
@imappalled 解决了 在桌面新建一个config的文件夹把default.json放进去
