### ISSUE TITLE
脚本运行出现 File "wechat_jump_auto.py", line 8, in <module>

### ISSUE THREAD

**Issue by Moosphan** [wangshub/wechat_jump_game#336]
完整信息：
```
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 8, in <module>
    from PIL import Image, ImageDraw
ImportError: No module named PIL
MoosdeMacBook-Pro:wechat_jump_game-master moos$ 
```

**Comment by littlepinecone** [comment]
pip install pillow
//装个pycharm多省事

**Comment by Moosphan** [comment]
```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/cy/l4bsfd117hj61ln8k19ndmmc0000gn/T/pip-build-u6o7NP/olefile/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/cy/l4bsfd117hj61ln8k19ndmmc0000gn/T/pip-0EhHEQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/cy/l4bsfd117hj61ln8k19ndmmc0000gn/T/pip-build-u6o7NP/olefile/
```

**Comment by F-loat** [comment]
sudo
