### ISSUE TITLE
IOError: cannot identify image file './autojump.png'

### ISSUE THREAD

**Issue by violetGirl** [wangshub/wechat_jump_game#341]
=====
Screen: Physical size: 1080x1920
Density: Physical density: 400
DeviceType: HUAWEI P8max
=====
List of devices attached
HEE6R16118004006        device

Traceback (most recent call last):
  File "d:/Python27/jump/wechat_jump_auto.py", line 234, in <module>
    main()
  File "d:/Python27/jump/wechat_jump_auto.py", line 221, in main
    im = Image.open('./autojump.png')
  File "D:\Python27\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by LisonFan** [comment]
Windows 平台可暂时用 #310 解决
