### ISSUE TITLE
魅族MX5不行！

### ISSUE THREAD

**Issue by huozhidiewu** [wangshub/wechat_jump_game#349]
python2 wechat_jump_auto.py  
Load config file from /home/ljt/wechat_jump_game/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
=====           
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MX5
=====
List of devices attached 
85GACMCNBB9C	device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 234, in <module>
    main()
  File "wechat_jump_auto.py", line 221, in main
    im = Image.open('./autojump.png')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1980, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file

**Comment by chilyoniki** [comment]
一模一样的情况老兄，我是macbookpro+魅族MX5，截图延时也该了，手机上的大大小小相关参数也改了还是同样的错误 211行
