### ISSUE TITLE
请问PermissionError: [Errno 13] 是怎么回事

### ISSUE THREAD

**Issue by YXX-to-YY** [wangshub/wechat_jump_game#356]
具体信息如下：
```
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 4X
OS: win32
Python: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
=====
List of devices attached
358b34d80204    device

Traceback (most recent call last):
  File "D:\Codes\Pyhon3\wechat_jump_game-master\wechat_jump_auto.py", line 236, in <module>
    main()
  File "D:\Codes\Pyhon3\wechat_jump_game-master\wechat_jump_auto.py", line 222, in main
    pull_screenshot()
  File "D:\Codes\Pyhon3\wechat_jump_game-master\wechat_jump_auto.py", line 83, in pull_screenshot
    f = open('autojump.png', 'wb')
PermissionError: [Errno 13] Permission denied: 'autojump.png'
```

**Comment by yuanhuikai** [comment]
你这个是没写的权限啊，用管理员？

**Comment by YXX-to-YY** [comment]
@yuanhuikai  确实是没有用到管理员，被自己搞蒙了，谢谢了
