### ISSUE TITLE
adb连上了，可为什么会出现这个种情况呢？

### ISSUE THREAD

**Issue by LIHAOCHI** [wangshub/wechat_jump_game#361]
在执行wechat_jump_auto.py时遇到的，机型LG G5 SE，分辨率2560x1440，我用的就是2560x1440的config，而且也把.py文件和default还有config都放在一个文件夹里了，怎么还会这样呢？

-`Traceback (most recent call last):
  File "E:\wechat\wechat_jump_auto.py", line 57, in <module>
    config = open_accordant_config()
  File "E:\wechat\wechat_jump_auto.py", line 43, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\wechat/config/default.json'`

求大神指导

**Comment by LIHAOCHI** [comment]
![default](https://user-images.githubusercontent.com/16367286/34462920-9d1ca9c8-ee88-11e7-987a-74959748c7f1.png)
