### ISSUE TITLE
安卓运行脚本报错

### ISSUE THREAD

**Issue by NinthCode** [wangshub/wechat_jump_game#363]
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: Che1-CL20
OS: win32
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
**********
List of devices attached
8c34fd69c42c    device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by bsaby** [comment]
try #347
