### ISSUE TITLE
运行之后手机上不动

### ISSUE THREAD

**Issue by manmanmango** [wangshub/wechat_jump_game#387]
Load config file from D:\Users\yunlong\Desktop\wechat_jump_game-master/config/1920x1080/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
c20ca1c2        device

scan_start_y:  690
1514745592 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745594 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745597 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745600 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745603 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745605 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
scan_start_y:  690
1514745608 338.54135338345867 1109 788.5 849.2162542517401
adb shell input swipe 320 410 320 410 723
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 229, in main
    jump(math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2))
  File "wechat_jump_auto.py", line 129, in jump
    os.system(cmd)
KeyboardInterrupt

-
就一直这样手机上不动，上面坐标也是没变

**Comment by manmanmango** [comment]
我发现原因了，调试的安全设置没开
现在正常使用了，
可为什么都只有5分6分？？
