### ISSUE TITLE
只能运行auto，手动模式opencv无法调出

### ISSUE THREAD

**Issue by Yjunlang** [wangshub/wechat_jump_game#391]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in cv::resize, file C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp, line 4044
Traceback (most recent call last):
  File "wechat_jump.py", line 15, in <module>
    template = cv2.resize(template, (0, 0), fx=scale, fy=scale)
cv2.error: C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize

**Comment by RichardWeiYang** [comment]
我用了auto也不行，报这个错

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 236, in <module>
    main()
  File "wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
目前好像不支持windows

**Comment by F-loat** [comment]
有人说重启了电脑就行了
