### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Romain-Chen** [wangshub/wechat_jump_game#395]
Load default config
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: HUAWEI P7-L07
OS: win32
Python: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
**********
Traceback (most recent call last):
  File "D:\ADB\platform-tools\wechat_jump_auto.py", line 236, in <module>
    main()
  File "D:\ADB\platform-tools\wechat_jump_auto.py", line 223, in main
    im = Image.open('./autojump.png')
  File "C:\Program Files\Python36\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
#325
