### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by xq598359628** [wangshub/wechat_jump_game#403]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: R7c
=====
List of devices attached
49eefe14        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 234, in <module>
    main()
  File "wechat_jump_auto.py", line 221, in main
    im = Image.open('./autojump.png')
  File "D:\develop\Anaconda3\lib\site-packages\PIL\Image.py", line 2519, in open

    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
#325
