### ISSUE TITLE
运行pip install -r requirements.txt时报错如下，哪位老哥知道呢

### ISSUE THREAD

**Issue by alivesunxiao** [wangshub/wechat_jump_game#41]
DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-sZqIwC-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by Lpmvb** [comment]
sudo执行

**Comment by cjy825** [comment]
Operation not permitted  没有权限咯 楼上正解  可以su root直接获得权限再用这句命令

**Comment by alivesunxiao** [comment]
q切换成root账户依然报同样错误

**Comment by alivesunxiao** [comment]
切换成root依然报同样错误

**Comment by cjy825** [comment]
这就不清楚了 - - 我也是小白一个  只能建议你去ubuntu里装库  windows我装的时候也是问题一大推

**Comment by linsuiyuan** [comment]
你的系统是macOS吧，

 1、重启电脑，按command+R进入恢复模式，点击菜单【实用工具】，打开【终端】，输入 csrutil disable 
 2、重启电脑，正常进入，打开【终端】输入 csrutil  status

这是macosx 10.11 以上的系统使用了Rootlees，可以理解为一个更高等级的内核保护，系统会默认锁定/system , /sbin , /usr这三个目录，
通过上面方法可以将这个保护关闭。

如果没有关闭，安装一些软件时会出现
Operation not permitted

**Comment by lyrical1991** [comment]
我也一样报错，想问下是什么情况，我的是linux

**Comment by MaYunFei** [comment]
我的 sudo 执行 成功， mac 13.2

**Comment by luogao** [comment]
pip install -r requirements.txt --user -U

**Comment by luogao** [comment]
`pip install -r requirements.txt --user -U`

**Comment by luogao** [comment]
[http://xiaorui.cc/2016/03/27/%E8%A7%A3%E5%86%B3mac-osx%E4%B8%8Bpip%E5%AE%89%E8%A3%85ipython%E6%9D%83%E9%99%90%E7%9A%84%E9%97%AE%E9%A2%98/](url)
