### ISSUE TITLE
MI 4LTE Error Message

### ISSUE THREAD

**Issue by yfdoor** [wangshub/wechat_jump_game#427]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 4LTE
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
4fbf9956        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "D:\Program Files\Python\Python36\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by F-loat** [comment]
#325
