### ISSUE TITLE
红米note2

### ISSUE THREAD

**Issue by tobealion** [wangshub/wechat_jump_game#434]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 2
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]

**Comment by tobealion** [comment]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: Redmi Note 2
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)
]
**********
List of devices attached
NZY9EQWWVGIZTS6P        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\sit
e-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by tobealion** [comment]
看了一位老铁的解决方法
把def pull_screenshot():
改成了：
    os.system('adb shell /system/bin/screencap -p /sdcard/screenshot.png')
    os.system('adb pull /sdcard/screenshot.png ./autojump.png')
运行后小人不会跳：
打开USB调试（安全设置）
大家刷的开心：）
