### ISSUE TITLE
不知道哪点没弄对

### ISSUE THREAD

**Issue by ATNX** [wangshub/wechat_jump_game#446]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: SM-G9300
OS: win32
Python: 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
55440d30        device

Traceback (most recent call last):
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 212, in load
    s = read(self.decodermaxblock)
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\PngImagePlugin.py", line 592, in load_read
    cid, pos, length = self.png.read()
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\PngImagePlugin.py", line 113, in read
    length = i32(s)
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\_binary.py", line 76, in i32be
    return unpack(">I", c[o:o+4])[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 345, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 194, in find_piece_and_board
    im_pixel=im.load()
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\ImageFile.py", line 217, in load
    raise IOError("image file is truncated")
OSError: image file is truncated

**Comment by gallonyin** [comment]
把def pull_screenshot():
方法体改成：
os.system('adb shell /system/bin/screencap -p /sdcard/screenshot.png')
os.system('adb pull /sdcard/screenshot.png ./autojump.png')
原来的用#注释掉或删掉
亲测可行

**Comment by ATNX** [comment]
改了之后 能自己跳 但是跳不准 ，就成功一次 后面依然不行，这是报错信息
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1440x2560
Density: Physical density: 640
DeviceType: SM-G9300
OS: win32
Python: 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
**********
List of devices attached
55440d30        device

Traceback (most recent call last):
  File "wechat_jump_auto.py", line 360, in <module>
    main()
  File "wechat_jump_auto.py", line 347, in main
    im = Image.open('./autojump.png')
  File "C:\Users\alber\Anaconda3\lib\site-packages\PIL\Image.py", line 2519, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'
