### ISSUE TITLE
删除autojump.png错误

### ISSUE THREAD

**Issue by shequ123** [wangshub/wechat_jump_game#474]
```
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 381, in <module>
    main()
  File "wechat_jump_auto.py", line 365, in main
    check_screenshot()
  File "wechat_jump_auto.py", line 354, in check_screenshot
    check_screenshot()
  File "wechat_jump_auto.py", line 344, in check_screenshot
    os.remove('autojump.png')
WindowsError: [Error 32] : 'autojump.png'
```

**Comment by shequ123** [comment]
Screen: 
Density: 
DeviceType: 
OS: win32
Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]

**Comment by jackunwen** [comment]
问题解决了吗 我也有这个问题
