### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by t514235260** [wangshub/wechat_jump_game#503]
Traceback (most recent call last):
  File ".\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  File ".\wechat_jump_auto.py", line 44, in open_accordant_config
    with open('{}/config/default.json'.format(sys.path[0]), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory:

**Comment by BruceGui** [comment]
config 目录下没有 default.json 文件，你是在那个目录运行的，试着从其他目录找 .json 配置文件，重命名为 default.json 就行了

**Comment by qixiangnan1996** [comment]
谢谢，师恩感谢

**Comment by t514235260** [comment]
config已经在目录内放入default.json文件
Load default config
Traceback (most recent call last):
  File ".\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  File ".\wechat_jump_auto.py", line 46, in open_accordant_config
    return json.load(f)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 1 (char 131)
