### ISSUE TITLE
浮点变量报错

### ISSUE THREAD

**Issue by Cao-czy** [wangshub/wechat_jump_game#512]
Traceback (most recent call last):
  File "C:\Users\Cao\Downloads\wechat_jump_game-master\wechat_jump_auto.py", line 288, in <module>
    main()
  File "C:\Users\Cao\Downloads\wechat_jump_game-master\wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "C:\Users\Cao\Downloads\wechat_jump_game-master\wechat_jump_auto.py", line 202, in find_piece
_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by Vg1ee** [comment]
修复了，请更新

**Comment by xurancrazy** [comment]
改成for j in range(int(board_x_start), int(board_x_end)):
