### ISSUE TITLE
python3不能自动运行，可以手点

### ISSUE THREAD

**Issue by kamike** [wangshub/wechat_jump_game#519]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 5
OS: win32
Python: 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
**********
采用方式2获取截图
scan_start_y:  690
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by kamike** [comment]
我加了个for j in range(int(board_x_start),int( board_x_end)):就行了
