### ISSUE TITLE
Broken PNG file报错

### ISSUE THREAD

**Issue by Vg1ee** [wangshub/wechat_jump_game#524]
Traceback (most recent call last):
  File "wechat_jump_auto4.py", line 288, in <module>
    main()
  File "wechat_jump_auto4.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto4.py", line 158, in find_piece_and_board
    im_pixel=im.load()
  File "/Library/Python/2.7/site-packages/PIL/ImageFile.py", line 214, in load
    s = read(self.decodermaxblock)
  File "/Library/Python/2.7/site-packages/PIL/PngImagePlugin.py", line 593, in load_read
    cid, pos, length = self.png.read()
  File "/Library/Python/2.7/site-packages/PIL/PngImagePlugin.py", line 117, in read
    raise SyntaxError("broken PNG file (chunk %s)" % repr(cid))
SyntaxError: broken PNG file (chunk 'AT\xe0\xaf')

**Comment by xiatianyu** [comment]
我这里也频繁报这个错 

程序版本号：1.1.1
**********
Screen: Physical size: 1440x2560
Density: Physical density: 560
DeviceType: Nexus 6P
OS: linux2
Python: 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
