### ISSUE TITLE
一加5，wechat_jump_auto.py打开闪退，手动运行后出现issue

### ISSUE THREAD

**Issue by Wyjaye** [wangshub/wechat_jump_game#528]
**********
Screen: Physical size: 1080x1920
Density: Physical density: 420
DeviceType: ONEPLUS A5000
OS: win32
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
**********
采用方式2获取截图
scan_start_y:  690
Traceback (most recent call last):
  File "C:\Users\Administrator\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 288, in <module>
    main()
  File "C:\Users\Administrator\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "C:\Users\Administrator\wechat_jump_game-master\wechat_jump_game-master\wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by zengke123** [comment]
取坐标取成小数了，for j in range(board_x_start, board_x_end)改成
for j in range(int(board_x_start), int(board_x_end))试试

**Comment by coioc** [comment]
同时一加5，跳的最多不到100，你的参数是怎么该的呀？现在如何了

**Comment by wangshub** [comment]
我的就是一加5，现在测试正常，利用1920*1080的配置就可以
