### ISSUE TITLE
这是什么意思？？？

### ISSUE THREAD

**Issue by wangwg1994** [wangshub/wechat_jump_game#530]
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by Vg1ee** [comment]
#501
