### ISSUE TITLE
Python 解析json的问题吗

### ISSUE THREAD

**Issue by t514235260** [wangshub/wechat_jump_game#531]
Load default config
Traceback (most recent call last):
  File ".\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  File ".\wechat_jump_auto.py", line 46, in open_accordant_config
    return json.load(f)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\t5142\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 1 (char 132)

**Comment by MrLevo520** [comment]
解决方案详见：https://www.crifan.com/python_json_loads_valueerror_expecting_property_name_line_1_column_1_char_1/
