### ISSUE TITLE
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'autoju mp.png'

### ISSUE THREAD

**Issue by lwjustsoso** [wangshub/wechat_jump_game#540]
D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master>adb devi
ces
List of devices attached
6O5402A06142    device

D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master>"D:\Docu
ment And Settings2\Administrator\Desktop\wechat_jump_game-master\wechat_jump_aut
o.py"
Load config file from D:\Document And Settings2\Administrator\Desktop\wechat_jum
p_game-master/config/1280x720/config.json
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: HM 2A
OS: win32
Python: 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.
1900 64 bit (AMD64)]
**********
Traceback (most recent call last):
  File "D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master\
wechat_jump_auto.py", line 262, in check_screenshot
    Image.open('./autojump.png').load()
  File "C:\Program Files\Anaconda3\lib\site-packages\PIL\Image.py", line 2317, i
n open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master\
wechat_jump_auto.py", line 288, in <module>
    main()
  File "D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master\
wechat_jump_auto.py", line 271, in main
    check_screenshot()
  File "D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master\
wechat_jump_auto.py", line 266, in check_screenshot
    check_screenshot()
  File "D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master\
wechat_jump_auto.py", line 256, in check_screenshot
    os.remove('autojump.png')
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'autoju
mp.png'

D:\Document And Settings2\Administrator\Desktop\wechat_jump_game-master>

**Comment by lwjustsoso** [comment]
为啥 我用手动点的 点了但是手机上没有反应

**Comment by chg0901** [comment]
我的测试也出现了问题

```
如果你的脚本无法工作，上报issue时请copy如下信息:
**********        
Screen: Physical size: 720x1280        
Density: Physical density: 320        
DeviceType: CAM-L32        
OS: win32        
Python: 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
**********
Traceback (most recent call last):
  File "E:/CodingWorkspace/pycharmWorkplace/wechat_jump_game-master/wechat_jump_auto.py", line 209, in check_screenshot
    Image.open('./autojump.png').load()
  File "E:\WorkingSoftware\Anaconda3\lib\site-packages\PIL\Image.py", line 2349, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/CodingWorkspace/pycharmWorkplace/wechat_jump_game-master/wechat_jump_auto.py", line 238, in <module>
    main()
  File "E:/CodingWorkspace/pycharmWorkplace/wechat_jump_game-master/wechat_jump_auto.py", line 220, in main
    check_screenshot()
  File "E:/CodingWorkspace/pycharmWorkplace/wechat_jump_game-master/wechat_jump_auto.py", line 213, in check_screenshot
    check_screenshot()
  File "E:/CodingWorkspace/pycharmWorkplace/wechat_jump_game-master/wechat_jump_auto.py", line 203, in check_screenshot
    os.remove('autojump.png')
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'autojump.png'

Process finished with exit code 1
```

**Comment by lwjustsoso** [comment]
screenshot_way = 2 改为screenshot_way = 0 即可正常工作了

**Comment by chg0901** [comment]
@lwjustsoso 
我修改了这行代码，应该是我这里的问题是保存图片不成功造成的，编码格式出问题
```
def pull_screenshot():
    '''
    新的方法请根据效率及适用性由高到低排序
    '''
    global screenshot_way
    if screenshot_way == 2 or screenshot_way == 1:
        process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
        screenshot = process.stdout.read()
        if screenshot_way == 2:
            binary_screenshot = screenshot.replace(b'\r\r\n', b'\n')#screenshot.replace(b'\r\n', b'\n')
        else:
            binary_screenshot = screenshot.replace(b'\r\r\n', b'\n')
        f = open('autojump.png', 'wb')
        f.write(binary_screenshot)
        f.close()
    elif screenshot_way == 0:
        os.system('adb shell screencap -p /sdcard/autojump.png')
        os.system('adb pull /sdcard/autojump.png .')

```
