### ISSUE TITLE
三星s8

### ISSUE THREAD

**Issue by niceokf** [wangshub/wechat_jump_game#547]
MacBook:wechat_jump_game-master nice$ adb devices
List of devices attached
98899a354739314233	device

MacBook:wechat_jump_game-master nice$ python wechat_jump_auto.py
Load default config
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 57, in <module>
    config = open_accordant_config()
  File "wechat_jump_auto.py", line 45, in open_accordant_config
    return json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 6 column 5 (char 129)
MacBook:wechat_jump_game-master nice$

**Comment by wangshub** [comment]
应该是配置文件没找对，麻烦再看下
