### ISSUE TITLE
求助，百度好久，不会

### ISSUE THREAD

**Issue by axxxxa** [wangshub/wechat_jump_game#549]
自动程序运行报错，如下。

Traceback (most recent call last):
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 61, in <module>
    config = open_accordant_config()
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 34, in open_accordant_config
    screen_size = _get_screen_size()
  
File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 50, in _get_screen_size
    size_str = os.popen('adb shell wm size').read()
  
File "D:\Program Files\lib\os.py", line 978, in popen
    bufsize=buffering)
  
File "D:\Program Files\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  
File "D:\Program Files\lib\subprocess.py", line 990, in _execute_child
    
startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by cxgreat2014** [comment]
电脑上没安装adb吧？

**Comment by axxxxa** [comment]
装了，还调用过

**Comment by MrLevo520** [comment]
目前正在解决这个问题，资源已提交，晚些时候会更新

**Comment by axxxxa** [comment]
谢谢

**Comment by axxxxa** [comment]
我的adb安装应该没问题啊，都出结果了。
List of devices attached
WTKDU16829008551      devices
还是不行
