### ISSUE TITLE
信息报错，华为手机

### ISSUE THREAD

**Issue by ShallowGreen** [wangshub/wechat_jump_game#555]
```
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 720x1280
Density: Physical density: 320
DeviceType: HUAWEI G7-TL00
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
**********
采用方式1获取截图
scan_start_y:  426
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 289, in <module>
    main()
  File "wechat_jump_auto.py", line 278, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "wechat_jump_auto.py", line 202, in find_piece_and_board
    for j in range(board_x_start, board_x_end):
TypeError: 'float' object cannot be interpreted as an integer
```

有人解决一下不

**Comment by zengke123** [comment]
for j in range(board_x_start, board_x_end):

改成

for j in range(int(board_x_start), int(board_x_end)):

**Comment by Vg1ee** [comment]
#501
