### ISSUE TITLE
iOS + Mac 使用方法（总结）

### ISSUE THREAD

**Issue by LBinin** [wangshub/wechat_jump_game#561]
iOS + Mac 使用方法

首先说明，不是原创~ 因为自己也是第一次接触 WebDriverAgent，所以碰壁了几次，现在归纳总结一下，以此分享给需要的人~

感谢下面各位大大的方法给我参考

[@shiniv](https://github.com/wangshub/wechat_jump_game/issues/162#issuecomment-354552074)

[@kwailamchan](https://github.com/wangshub/wechat_jump_game/issues/379#issuecomment-354618984)

以及 wangshub 大大的介绍 [iOS 手机操作步骤](https://github.com/wangshub/wechat_jump_game#ios-%E6%89%8B%E6%9C%BA%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%AA%A4)

在项目开始前可以先克隆该项目并安装依赖，因为这个过程可能会比较漫长

```
git clone https://github.com/wangshub/wechat_jump_game.git

pip3 install --pre facebook-wda
pip3 install -r requirements.txt
```

---

### 操作步骤：

1. 克隆 「 **WebDriverAgent** 」 项目
	
	```
	git clone https://github.com/facebook/WebDriverAgent
	```
	
2. 安装 「  **Carthage** 」，因为后面的脚本会使用 Carthage，安装所有依赖
	
	```
	brew install carthage
	```

3. 执行脚本

	```
	./Scripts/bootstrap.sh
	```

4. 执行完脚本后，打开 `WebDriverAgent.xcodeproj` 并按照教程修改。教程地址：[ATX 文档 - iOS 真机如何安装 WebDriverAgent](https://testerhome.com/topics/7220)。

	这里有几点内容说一下：
	1. `WebDriverAgentLib` 和 `WebDriverAgentRunner` 都要设置好证书。
	2. 如果出现错误，提示 `cannot be registered to your development team. Change your bundle identifier` 之类的提示，到 `WebDriverAgentLib` 或者 `WebDriverAgentRunner` （ 签名失败的那一个 Target ）的 「Build Setting」 中，更改 `Product Bundle Identifier` 里的内容改成 `com.你的名称.WebDriverAgentRunner` 等类似字符串。
	3. 在菜单栏 Product -> Destination 中选择你的设备。
	4. 在菜单栏 Product -> Scheme 中选择 `WebDriverAgentRunner` 。
	4. 最后运行 Product -> Test。
	5. 如果成功的话，手机上会出现一个名为「WebDriverAgent」没有图标的应用，不用管他。
	6. 此时 Xcode 的控制台会输出 `ServerURLHere->http://localhost:8100<-ServerURLHere` 类似的提示。（ 没有看到控制台的话可以在菜单栏中 View -> Debug Area -> Activate Console 打开控制台 ）
	7. 此时用电脑打开 `http://localhost:8100/status` （ 在控制台给出的 URL 后加上 `/status` 查看手机状态 ），如果出现 JSON 内容则表明成功，直接跳到第 8 步骤。
	8. 不过一些朋友现在打开可能也看不到，因为端口还没有转发到Mac，接着往下走，看第 5 步骤。

5. 安装端口转发工具 「libimobiledevice」

	```
	brew install libimobiledevice
	```

6. 安装完 libimobiledevice 以后，开始转发端口
	
	```
	iproxy 8100 8100
	```
	
	此时不要关闭终端或者终止运行。

7. 转发成功后访问 [http://localhost:8100/status](http://localhost:8100/status) 将会有 JSON 内容显示。

8. 再打开一个新的终端进入到该项目 `wechat_jump_game` 目录下面

9. 拷贝 `./config/iPhone` 目录下对应的设备配置文件，重命名并替换到 `./config.json`

11. 手机打开微信「跳一跳」小游戏，点击开始。

12. 运行 py

	```
	python3 wechat_jump_auto_iOS.py
	```
	
13. 要终止的话随时可以 `ctrl + c` 终止运行。

**Comment by sexdevil** [comment]
libimobiledevice 这个我mac上安装失败 checking whether the C compiler works... no
configure: error: in `/private/tmp/pkg-config20180102-4336-kpv3s3/pkg-config-0.29':
configure: error: C compiler cannot create executables

**Comment by LBinin** [comment]
@sexdevil 应该是 gcc 没有装好吧？

**Comment by sexdevil** [comment]
brew install gcc也是这个错误

**Comment by LBinin** [comment]
@sexdevil 那你试试重新安装一下 [Homebrew](https://brew.sh/) 然后 `brew doctor` 下看看

**Comment by sexdevil** [comment]
wda.WDAError: WDAError(status=1, value=Unhandled endpoint: /screenshot -- http://localhost:8100/ with parameters {
    wildcards =     (
        screenshot
    );
})
运行起来报这个错

**Comment by SIXSIXSIXX** [comment]
为什么我运行的时候要求我输入keychain access的密码

**Comment by leegang** [comment]
python  wechat_jump_auto_iOS.py

报如下错误有谁遇到过吗？

```
$ 
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d70860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/leegang/anaconda/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x105d70860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d70860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 70, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d70860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/leegang/anaconda/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/leegang/anaconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x105d8f080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d8f080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 53, in <module>
    s = c.session()
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/wda/__init__.py", line 75, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d8f080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

**Comment by tulermos** [comment]
执行./Scripts/bootstrap.sh这个命令，会报下面这个错误，有大神知道是怎么回事吗

*** Checking out RoutingHTTPServer at "v1.0.1"
*** xcodebuild output can be found in /var/folders/1k/2szc3j4j147cpkr_f3xbgn_00000gn/T/carthage-xcodebuild.mjHY30.log
A shell task (/usr/bin/xcrun xcodebuild -project /Users/tulermos/WebDriverAgent/Carthage/Checkouts/RoutingHTTPServer/RoutingHTTPServer.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 72:
xcrun: error: unable to find utility "xcodebuild", not a developer tool or in PATH

**Comment by leegang** [comment]
@SIXSIXSIXX
直接输入就可以了

**Comment by inmWang** [comment]
@tulermos 跟你错误一样 有大神知道怎么解决吗

**Comment by LBinin** [comment]
@leegang 用 python3

**Comment by leegang** [comment]
@LBinin 我用的就是 Python 3啊。

**Comment by tulermos** [comment]
'RoutingHTTPServer/RoutingConnection.h' file not found   运行WebDriverAgent报这个错，有大神知道怎么解决吗？

**Comment by CoderZZHe** [comment]
@tulermos 选择xcode版本、、xcode->Preferences->Locations->Conmand Line Tools、这步操作完后再重新git clone...

**Comment by tulermos** [comment]
/Users/tulermos/Downloads/WebDriverAgent-master/WebDriverAgentRunner/UITestingUITests.m:12:9: fatal error: 'WebDriverAgentLib/FBDebugLogDelegateDecorator.h' file not found
#import <WebDriverAgentLib/FBDebugLogDelegateDecorator.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1
运行WebDriverAgent又报了这个错误

**Comment by tulermos** [comment]
localhost:wechat_jump_game-master tulermos$ python3 wechat_jump_auto_iOS.py
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 6, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'
localhost:wechat_jump_game-master tulermos$    
执行python3 wechat_jump_auto_iOS.py 报这个错误，请问有大神知道是什么原因吗

**Comment by TeacherXue** [comment]
@leegang 我也报的这个

**Comment by leegang** [comment]
@tulermos 
你需要先安装 wda
`pip  install  facebook-wda`

**Comment by HarrisonLin** [comment]
Product  Test的时候，就直接报错了。

![image](https://user-images.githubusercontent.com/10679283/34475529-eec1716a-efc7-11e7-9ce5-df031ff04816.png)

Xcode 8.3 bata ，已经很新的。

**Comment by LBinin** [comment]
@HarrisonLin 11.2 真机调试需要 Xcode9.2 以上或者下载真机调试包

**Comment by lishinan0909** [comment]
@tulermos 依赖没安装  运行这两句 brew install carthage    ./Scripts/bootstrap.sh

**Comment by lishinan0909** [comment]
@leegang 我也遇到了这个问题 怀疑是localhost的问题 运行test时给的地址不是 localhost:8100

**Comment by lishinan0909** [comment]
@leegang 感觉应该很多人都会遇到这种情况啊

**Comment by Joneze** [comment]
拷贝 ./config/iPhone 目录下对应的设备配置文件，重命名并替换到 ./config.json   这句不理解啊~~

**Comment by LBinin** [comment]
@Joneze 就是比如你是6、6s、7、8，把 `/config/iPhone` 下的 `6_config.json` 重命名为 `config.json` 后放到项目根目录。

**Comment by leegang** [comment]
@lishinan0909   
应该是wda相关的问题。我换了个电脑，重新做了一遍就ok了。可惜被刷分会被清掉。

**Comment by pheromone** [comment]
@LBinin 
我这里不管怎么link都不行.请问该怎么link.
<img width="523" alt="2018-01-02 10 15 59" src="https://user-images.githubusercontent.com/14305431/34486390-bb774526-f00a-11e7-9784-510415a7a02b.png">

**Comment by LBinin** [comment]
@pheromone `brew link carthage` 不行用么，可以重新安装 Homebrew 试试

**Comment by ChromiuMEndless** [comment]
运行wechat_jump_auto_iOS.py时遇到了这个错误跪求解决
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 31, in <module>
    config = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 24: invalid continuation byte

**Comment by yahoouchen** [comment]
@leegang 下面问题是怎么解决的？

python wechat_jump_auto_iOS.py

报如下错误有谁遇到过吗？

$ 
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x105d70860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/leegang/anaconda/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leegang/anaconda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)

**Comment by 814349837** [comment]
转发端口 一直Error Connecting to device
![image](https://user-images.githubusercontent.com/18303855/34508490-f6fd997c-f07a-11e7-8900-d1534287dde7.png)

**Comment by lucyios** [comment]
可以自动跳了，但是不超过50分，就挂了，衰

**Comment by AkaShark** [comment]
iphone5s用哪个json文件

**Comment by yahoouchen** [comment]
执行到这步的时候
brew install libimobiledevice
 iproxy 8100 8100

控制台一直显示waiting for connection

有知道问题的吗？

**Comment by KevinZK** [comment]
USB support 

# Install
$ brew install usbmuxd

# Start proxy
$ iproxy 8100 8100

**Comment by leegang** [comment]
@yahoouchen  没什么问题。你现在可以另开一个终端运行py程序了。

**Comment by yahoouchen** [comment]
@leegang  开启另一个终端也是不行继续运行会报错   而且http://localhost/:8100/status访问不了，http://localhost:8100/inspector有json数据 但是没有图像界面 
运行脚本python3 wechat_jump_auto_iOS.py 报错
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10be3ada0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last):
  File "/Users/UCS/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/UCS/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Users/UCS/anaconda3/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

**Comment by leon0204** [comment]
配置用的是6s
```
{
    "under_game_score_y": 200,
    "press_coefficient": 2.0,
    "piece_base_height_1_2": 13,
    "piece_body_width": 49,
    "swipe": {
        "x1": 375,
        "y1": 1055,
        "x2": 375,
        "y2": 1055
    }
}
```
每次跳到70左右就死了。为什么呢

**Comment by leegang** [comment]
@leon0204 
试试
` "press_coefficient": 1.99,`

**Comment by leon0204** [comment]
@leegang 还是不行，49就死了，可能还有什么其他原因呢？ py3 ，mac + iphone10.3.3 xcode 9.2

**Comment by leon0204** [comment]
@lucyios 
你现在可以了吗，我也是200就挂了

**Comment by ChyonM** [comment]
运行“wechat_jump_auto_iOS.py”这个的时候有这个错误 config.json和 .py放在一个文件夹下了 第一次接触 小白急求大神指点
-bash: import: command not found
-bash: import: command not found
-bash: import: command not found
-bash: import: command not found
-bash: import: command not found
from: can't read /var/mail/PIL
-bash: import: command not found
-bash: import: command not found
-bash: wechat_jump_auto_iOS.py: line 30: syntax error near unexpected token `('
-bash: wechat_jump_auto_iOS.py: line 30: `with open('config.json', 'r') as f:'

**Comment by shyh5** [comment]
@LBinin
请问，把/config/iPhone文件改成 _config.json放在项目根目录。。
这个项目根目录只指WebDriverAgent项目还是wechat_jump_game

**Comment by shyh5** [comment]
请问，我输出了地址，但是打不开。是什么原因

**Comment by MiniDingInitiative** [comment]
有没有遇到这个问题的，可以安装在手机上，但是test过后控制台显示
未能载入软件包“WebDriverAgentRunner”，因为未能找到其可执行文件的位置。 请尝试重新安装软件包。

**Comment by shyh5** [comment]
@yahoouchen  请问你的问题解决了吗，我遇到了和你一样的情况

**Comment by Allen0910** [comment]
转发端口的时候报下面的错误：
waiting for connection
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 4 (serial: b90fe287196d97e79c26e17bf1cb06f6060a3da8), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 4 (serial: b90fe287196d97e79c26e17bf1cb06f6060a3da8), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 4 (serial: b90fe287196d97e79c26e17bf1cb06f6060a3da8), port 8100
Error connecting to device!
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 4 (serial: b90fe287196d97e79c26e17bf1cb06f6060a3da8), port 8100
Error connecting to device!

**Comment by dandan0503** [comment]
@Allen0910 我也遇到你的问题，解决了吗？

**Comment by dandan0503** [comment]
@已解决
需要先运行这一句
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'platform=iOS Simulator,name=iPhone 6S' test
再运行
iproxy 8100 8100
就能有结果了

**Comment by saminlu** [comment]
@Allen0910 请问解决了么？求方法  iproxy 8100 8100
一直waiting for connection

**Comment by meilbn** [comment]
@saminlu 这个是正常的，浏览器打开 http://localhost:8100/status 看看有没有 JSON 数据，或者打开 http://localhost:8100/inspector 看看是否可以看到手机屏幕。

**Comment by fanspring** [comment]
我也遇到这个问题了，你解决了么

**Comment by fanspring** [comment]
我也遇到了问题-----未能载入软件包“WebDriverAgentRunner”
有解决的么

**Comment by ZengYueQin** [comment]
> 

How to solve this problem? I've seen also
