### ISSUE TITLE
oppor9s

### ISSUE THREAD

**Issue by menglingkun1011** [wangshub/wechat_jump_game#579]
如果你的脚本无法工作，上报issue时请copy如下信息:
**********
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: OPPO R9s
OS: win32
Python: 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 b
it (AMD64)]

报错：
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 356, in <module>
    main()
  File "wechat_jump_auto.py", line 343, in main
    im = Image.open('./autojump.png')
  File "F:\Anaconda3\lib\site-packages\PIL\Image.py", line 2572, in open
    % (filename if filename else fp))
OSError: cannot identify image file './autojump.png'

**Comment by binderclip** [comment]
代码怎么执行的？
