### ISSUE TITLE
运行 wechat_jump_auto.py 报错IOError:[Errno 0] Error

### ISSUE THREAD

**Issue by PebblerWon** [wangshub/wechat_jump_game#581]
```
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: FRD-AL00
OS: win32
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (I
ntel)]
**********Traceback (most recent call last):
  File "wechat_jump_auto.py", line 286, in <module>
    main()
  File "wechat_jump_auto.py", line 268, in main
    dump_device_info()
  File "wechat_jump_auto.py", line 247, in dump_device_info
    python=sys.version
IOError: [Errno 0] Error
```

**Comment by PebblerWon** [comment]
已解决，好像是命令行编码方式的问题。
