### ISSUE TITLE
运行了一段时间后报错

### ISSUE THREAD

**Issue by hexianqiao3755** [wangshub/wechat_jump_game#582]

**Comment by hexianqiao3755** [comment]
Screen: Physical size: 1080x1920
Density: Physical density: 480
DeviceType: MI 6
OS: darwin
Python: 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


Traceback (most recent call last):
  File "/Users/heqiao/Downloads/wechat_jump_game-master/wechat_jump_auto.py", line 288, in <module>
    main()
  File "/Users/heqiao/Downloads/wechat_jump_game-master/wechat_jump_auto.py", line 277, in main
    piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
  File "/Users/heqiao/Downloads/wechat_jump_game-master/wechat_jump_auto.py", line 158, in find_piece_and_board
    im_pixel=im.load()
  File "/Users/heqiao/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 255, in load
    raise_ioerror(err_code)
  File "/Users/heqiao/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
OSError: unrecognized data stream contents when reading image file

**Comment by wangshub** [comment]
暂时解决办法：这个时候可以重新运行程序，继续跳 @hexianqiao3755

**Comment by hexianqiao3755** [comment]
@wangshub  谢谢
