### ISSUE TITLE
刚才问的没有解决，再来一次

### ISSUE THREAD

**Issue by axxxxa** [wangshub/wechat_jump_game#589]
自己找了很久，问了别人，还是没明白。我adb运行成功了，出结果了。用的是自动安卓，有人说错在分辨率获取，无奈求解。

自动程序运行报错，如下。

Traceback (most recent call last):

File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 61, in 
config = open_accordant_config()

File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 34, in open_accordant_config
screen_size = _get_screen_size()

File "e:\wechat_jump_game-master\wechat_jump_auto.py", line 50, in _get_screen_size
size_str = os.popen('adb shell wm size').read()

File "D:\Program Files\lib\os.py", line 978, in popen
bufsize=buffering)

File "D:\Program Files\lib\subprocess.py", line 707, in init
restore_signals, start_new_session)

File "D:\Program Files\lib\subprocess.py", line 990, in _execute_child

startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by Wangxiao-pub** [comment]
C:\Users\Administrator>python D:\Develop\wechat_jump\wechat_jump_auto.py
Traceback (most recent call last):
  File "D:\Develop\wechat_jump\wechat_jump_auto.py", line 34, in <module>
    config = config.open_accordant_config()
  File "D:\Develop\wechat_jump\common\config.py", line 15, in open_accordant_con
fig
    screen_size = _get_screen_size()
  File "D:\Develop\wechat_jump\common\config.py", line 34, in _get_screen_size
    size_str = os.popen('adb shell wm size').read()
  File "D:\Develop\Python\lib\os.py", line 980, in popen
    bufsize=buffering)
  File "D:\Develop\Python\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Develop\Python\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

看来我们的错误是一样的，家里的笔记本同样的配置没问题，公司的台式就会出问题

**Comment by axxxxa** [comment]
我这个是笔记本，没办法。
