### ISSUE TITLE
报错Debug.dump_device_info()

### ISSUE THREAD

**Issue by Hasiy** [wangshub/wechat_jump_game#624]
Load config file from C:\Users\admin\Desktop\wechat_jump_game-master\Tools\adb/config/1920x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 238, in <module>
    main()
  File "wechat_jump_auto.py", line 219, in main
    Debug.dump_device_info()
  File "C:\Users\admin\Desktop\wechat_jump_game-master\Tools\adb\WechatJump\Debug.py", line 47, in dump_device_info
    device_str = os.popen('adb shell getprop ro.product.model').read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 2: illegal multibyte sequence

**Comment by Hasiy** [comment]
![q3c vk2 c6k p cl rvj5](https://user-images.githubusercontent.com/13153821/34475557-206a0ede-efc8-11e7-910c-c57d01ca48b6.png)

**Comment by athosss** [comment]
我的也是这个Debug.dump_device_info()问题，不过不一样，
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
**********Traceback (most recent call last):
  File "wechat_jump_auto1.py", line 356, in <module>
    main()
  File "wechat_jump_auto1.py", line 339, in main
    dump_device_info()
  File "wechat_jump_auto1.py", line 321, in dump_device_info
    python=sys.version
IOError: [Errno 0] Error

**Comment by Markluoelliot** [comment]
我之前也是这个原因，我的原因是我用的python2，应该用python3
