### ISSUE TITLE
无法识别autojump.png

### ISSUE THREAD

**Issue by jackunwen** [wangshub/wechat_jump_game#628]
**********
Screen: Physical size: 1920x1080
Density: Physical density: 240
DeviceType: GT-I9500
OS: win32
Python: 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]
**********
遇到问题：无法识别 autojump.png
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 288, in <module>
    main()
  File "wechat_jump_auto.py", line 271, in main
    check_screenshot()
  File "wechat_jump_auto.py", line 266, in check_screenshot
    check_screenshot()
  File "wechat_jump_auto.py", line 256, in check_screenshot
    os.remove('autojump.png')
WindowsError: [Error 32] : 'autojump.png'
改进和建议：无

**Comment by Pois-0N** [comment]
python3
