### ISSUE TITLE
运行 python3 wechat_jump_iOS_py3.py 后报错：retry to connect, error:

### ISSUE THREAD

**Issue by candz** [wangshub/wechat_jump_game#655]
麻烦大伙儿给看看
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c3e5fd0>: Failed to establish a new connection: [Errno 61] Connection refused',))
Traceback (most recent call last):
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10c3e5fd0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/sora/anaconda3/envs/wechat_env/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c3e5fd0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

**Comment by BeyoundCong** [comment]
一样 我的也是这个错误。

**Comment by JWWplus** [comment]
同样错误   举手

**Comment by JWWplus** [comment]
问题解决了，是mac的代理不对，修改后可以运行
下面是参考文章的原话
有些国产的iPhone机器通过手机的IP和端口还不能访问，此时需要将手机的端口转发到Mac上。

$ brew install imobiledevice
$ iproxy 8100 8100
使用iproxy --help 可以查到更具体的用法。 这时通过访问http://localhost:8100/status确认WDA是否运行成功。

而inspector的地址是http://localhost:8100/inspector， inspector是用来查看UI的图层，方便写测试脚本用的

**Comment by MemoryReload** [comment]
理论上来讲，如果手机上的调试服务器起了，是应该能连上的，但是不知道为什么，似乎走局域网连不通。不过，用iproxy实用USB连接，把手机端口代理到本机，然后访问本机ip的方式就可以。我以前做越狱的时候，ssh可以通过局域网连接手机的，iproxy只是更快一些。但是，wda貌似需要用USB连接。但是，模拟器用ip又可以访问，具体原因不知。

**Comment by MaosenZ** [comment]
我通过把`c = wda.Client()`改为c = wda.Client("http://192.168.1.85:8100")成功了，地址来自`wda`测试时输出的`ServerURLHere->http://192.168.1.85:8100<-ServerURLHere`

**Comment by shanerbo** [comment]
@MaosenZ 神了 有时候 hardcode真是无解 解决了我一宿的问题

**Comment by Sycooo** [comment]
你这个问题是阻止我成功运行的最后一道坎，我是这样搞的
新开个窗口
brew install libmobiledevice
iproxy 8100 8100

然后再运行 python3 wechat_jumo_auto_iOS.py

成功！

**Comment by longitachi** [comment]
我用`WebDriverAgent`测试输出的， 改成`c = wda.Client("http://192.168.1.188:8100")` 还是链接不上

**Comment by longitachi** [comment]
倒是用模拟器7plus 运行后出来了界面

**Comment by yunqu** [comment]
$ brew install usbmuxd
$ iproxy 8100 8100

这个是正解
iproxy会占用一个窗口 
所以需要再开一个窗口跑python的程序

**Comment by MemoryReload** [comment]
@longitachi 我那天去看了下官方的资料，说是有些国产手机，是没办法远程访问的，得通过USB，用代理访问，模拟器是没有任何问题可以通过局域网访问的。@MaosenZ 你的手机是不是国航，国行应该都会有这个病症。因为我用浏览器访问status页面，模拟器可以，真机用网页就不行，用usb连接用浏览正常，说明不是地址的问题，是局域网就连不上，真机。我猜想，你的机器应该不是国行吧。

**Comment by MemoryReload** [comment]
@yunqu 建议你装libmobiledevice全家桶，里面有好多好玩的宝贝。晚安，各位。😊

**Comment by longitachi** [comment]
@MemoryReload 手机是国行。现在可以了，我发现连着wifi就获取不到屏幕，用手机4g网络可以。 不过然并卵啊，分数已经提交不上去了

**Comment by yunqu** [comment]
@MemoryReload  那个package不好用 usbmuxd works for me 
另外我是美国版的iphone 6 plus 这个问题看起来不只是国行有

**Comment by MemoryReload** [comment]
@yunqu   偷偷告诉你，libdevicemobile是依赖于usbmuxd的，并且这个工具箱提供了很多其它工具，比如查看设备id，查看设备安装应用列表，上传文件到安装应用的沙盒目录，下载应用的沙盒目录，安装应用等等，我觉得很好用。

**Comment by yunqu** [comment]
@MemoryReload  我说错了 不是不好用 是安装不了……
