### ISSUE TITLE
运行报错,提示:NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by jacknonebug** [wangshub/wechat_jump_game#662]
Load config file from d:\wechat_jump_game/config/1920x1080/config.json
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 260, in <module>
    main()
  File "wechat_jump_auto.py", line 227, in main
    op = yes_or_no('请确保手机打开了 ADB 并连接了电脑，然后打开跳一跳并【开始游戏】后再用本程序，确定开始？')
  File "wechat_jump_auto.py", line 211, in yes_or_no
    i = raw_input(prompt)
NameError: name 'raw_input' is not defined

**Comment by binderclip** [comment]
是个 bug，已经修复了，请更新代码 https://github.com/wangshub/wechat_jump_game/pull/663
