### ISSUE TITLE
wecgat_jump_auto_iOS.py运行正常，WeChat_jump_iOS_py3.py运行失败。

### ISSUE THREAD

**Issue by MemoryReload** [wangshub/wechat_jump_game#696]
```
env) [heping@Totoro:~/Desktop/jump_automation_proj/wechat_jump_game 16:33]# python wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/Users/heping/Desktop/jump_automation_proj/wechat_jump_game/.env/lib/python3.6/site-packages/matplotlib/pyplot.py", line 116, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/heping/Desktop/jump_automation_proj/wechat_jump_game/.env/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/Users/heping/Desktop/jump_automation_proj/wechat_jump_game/.env/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py", line 17, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

wechat_jump_auto_iOS.py  脚本可以正常运行，可以完美跳跳跳！
wechat_jump_iOS.py3  脚本运行后，终端卡顿数秒之后，抛出以上错误。游戏界面没有任何反应。

Commit:   c8d93a568da711dbaa5b6e186b88caea1b9e4187
DeviceType:   iPhone 6Plus
OS:   iOS 11.2.1
Python:   Python 3.6.0

**Comment by binderclip** [comment]
使用 conda 的时候需要 conda install python.app，另外启动的时候使用 pythonw 启动

**Comment by MemoryReload** [comment]
@binderclip  我不喜欢conda,我用virtualenv创建虚拟环境。I'm old fashioned. 您知道怎么解决吗，或者告诉我问题的起因，我大概可以自己解决。thks!

**Comment by binderclip** [comment]
@MemoryReload 按 `RuntimeError: Python is not installed as a framework.` 搜索下？
我当时是那么解决的

**Comment by JWWplus** [comment]
[参考这个答案](https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python)

**Comment by MemoryReload** [comment]
@binderclip 简单的来说，就是我用virtualenv安装的python，不是以framework方式安装的，导致matplotlib在MacOS环境下的默认后端macosx无法正常工作。两种解决办法，按照famework方式重新安装，或者配置新的后端。我现在配置的后端为TkAgg，按照官方说的配置方式有四种，尝试其中三种，成功两种：
1、在你的$HOME下会有一个.matplotlib目录，在目录下创建配置文件.matplotlib，写入配置`backend: TkAgg`。（此方法可用，但是全局配置回影响所有的工程）

2、在倒入库时进行配置，注意对mpl的配置必须在倒入pyplot之前，否则无效。（此方法可用，但是更换后端时需要修改代码，但是不会影响所有的项目，只对引用的代码生效）
```
import matplotlib as mpl
mpl.use('TkAgg')
import matplotlib.pyplot as plt
```
3、环境变量（此方法未成功，报错找不到TkAgg后端，这个配置可以覆盖1中配置文件的设置）
```
> export MPLBACKEND="module://TkAgg"
> python simple_plot.py
> MPLBACKEND="module://TkAgg" python simple_plot.py

```
4、选项-d（由于官方已废弃此方式，没有实验）
`> python script.py -dbackend`
