### ISSUE TITLE
iphone手机有成功运行起来的吗

### ISSUE THREAD

**Issue by songhaoreact** [wangshub/wechat_jump_game#71]

**Comment by MQL9011** [comment]
有啊,配置好环境就行
![image](https://user-images.githubusercontent.com/11871158/34452142-b058ce92-ed73-11e7-9fb8-2f9e8f665a52.png)

**Comment by songhaoreact** [comment]
```
songhaodeMacBook-Pro:wechat_jump_game songhao$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'
```
### 这个依赖找不到是什么情况 没学过python 通过什么安装这个依赖呢

**Comment by imerovingian** [comment]
需要安装Facebook WebDriverAgent Python Client Library (not official)
pip install --pre facebook-wda

前提是要先安装WebDriverAgent，看这个帖子https://github.com/facebook/WebDriverAgent

**Comment by 0312birdzhang** [comment]
@MQL9011 什么机型，time_coefficient 参数分享一下 😃

**Comment by SiliconZou** [comment]
老铁运行python3 wechat_jump_iOS_py3.py报错HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1167825c0>: Failed to establish a new connection: [Errno 61] Connection refused',)) 怎么解决

**Comment by renzifeng** [comment]
@songhaoreact 老铁，我也卡到这一步了，怎么破

**Comment by SiliconZou** [comment]
@MQL9011 老铁我的问题是什么原因呢

**Comment by RickeyBoy** [comment]
@SiliconZou @renzifeng 
配置WDA的最后：有些国产的iPhone机器通过手机的IP和端口还不能访问，此时需要将手机的端口转发到Mac上。
```
$ brew install libimobiledevice
$ iproxy 8100 8100
```
这时如果访问 `http://localhost:8100/status` 能显示一堆JSON数据，就说明WDA运行成功
然后再试试，应该就可以了

**Comment by renzifeng** [comment]
@RickeyBoy 我这里可以获显示json数据，但是运行python文件时候就是这报错了`wechat_jump_game songhao$ python3 wechat_jump_iOS_py3.py
Traceback (most recent call last):
  File "wechat_jump_iOS_py3.py", line 1, in <module>
    import wda
ModuleNotFoundError: No module named 'wda'`

**Comment by RickeyBoy** [comment]
@renzifeng 感觉是你 [facebook-wda](https://github.com/openatx/facebook-wda) 没装好。
我记得就 `pip3 install --pre facebook-wda` 就行了（会不会是python的版本没有装对？）

**Comment by renzifeng** [comment]
`Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/wda'
`

**Comment by gavin971** [comment]
@MQL9011 WebDriverAgent没有team证书，个人的免费的可以么？

**Comment by littcc** [comment]
HTTPConnectionPool 错误的话, 在创建一个 wda.Client 时 讲手机的 IP及端口传入 https://github.com/openatx/facebook-wda

**Comment by songhaoreact** [comment]
我怀疑也是python版本的问题 mac自带的是2.7 然后我通过homebrew安装的3版本

**Comment by SiliconZou** [comment]
@RickeyBoy 运行iproxy 8100 8100后一直是waiting for connection，就是连接不上 是什么原因呢

**Comment by jacentsao** [comment]
哪位知道这个错误怎么处理

```
File "wechat_jump_iOS_py3.py", line 15, in <module>
    s = c.session()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/wda/__init__.py", line 77, in httpdo
    retjson = response.json()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by SIXSIXSIXX** [comment]
python3 wechat_jump_iOS_py3.py
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11391b390>: Failed to establish a new connection: [Errno 61] Connection refused',))
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)

求大神怎么解决 我8100/status 能用

**Comment by SIXSIXSIXX** [comment]
请问有没有iphone6 的参数~~谢谢

**Comment by imerovingian** [comment]
iphone6的参数是 0.00195

**Comment by imerovingian** [comment]
retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded 
这个问题可以安装 iproxy解决
https://github.com/libimobiledevice/libusbmuxd

**Comment by renzifeng** [comment]
@imerovingian 这个怎么安装

**Comment by SiliconZou** [comment]
![img_2017](https://user-images.githubusercontent.com/20011796/34453332-26ac1c7a-ed8d-11e7-8e92-922a2f9ee217.PNG)
已完美运行，多谢各位大佬

**Comment by 0312birdzhang** [comment]
@SiliconZou 自动运行的吗？

**Comment by smallbull** [comment]
遇到应用内无法截图的问题，试了下返回主页面，是可以跑起来的。

**Comment by renzifeng** [comment]
已完美运行 接下来怎么玩

**Comment by SiliconZou** [comment]
@0312birdzhang iOS上我是手动点击的😂，然后改参数值，我用的是这个time_coefficient = 0.00200

**Comment by 0312birdzhang** [comment]
@SiliconZou Orz，我也手动点击一会，感觉虽然可以一直玩下去，但是不能解放双手啊 😂

**Comment by SIXSIXSIXX** [comment]
你们有没有试过截出来的图有时候不太对，就是箱子都还没显示出来就截图了

**Comment by SiliconZou** [comment]
@0312birdzhang 安卓上的好像可以自动运行，iOS上的改一下逻辑应该也可以吧

**Comment by HotWordland** [comment]
@smallbull 微信应用内无法截图:
将微信结束掉再打开

**Comment by 0312birdzhang** [comment]
@SiliconZou 嗯，做一个伸手党吧，等大佬把两个逻辑合并一下 😅

**Comment by LucasDvp** [comment]
IOS可以自动运行吗？需要一直自己在Python里面点吗？

**Comment by GhostClock** [comment]
@imerovingian 
已经设置好端口转发` iproxy 8100 8100` 可是还是不行

**Comment by siitao** [comment]
为什么我运行起来是这个界面
![image](https://user-images.githubusercontent.com/16183292/34456072-dc37d0bc-edc8-11e7-9dc5-14661e5cfc8f.png)

**Comment by cultivater** [comment]
<img width="512" alt="default" src="https://user-images.githubusercontent.com/32637529/34459680-3167af80-ee32-11e7-9bd6-f7d3f847337c.png">
这个问题无解了吗。。。看到好多朋友问这个问题都没有解决。。。

**Comment by Abysman** [comment]
请问下WDA下签名证书bundle那一块是怎么处理的？无法build和test起来

**Comment by Yammmy** [comment]
@Abysman https://forums.developer.apple.com/thread/63957 可能你选择好点左上角你的设备

**Comment by DIVEINBLUE** [comment]
@SiliconZou  老铁，iproxy 8100 8100的时候一直是waiting for connection 是怎么解决的？

**Comment by 2649073896** [comment]
确实是版本问题。我的mac里有python 2.7和3.6。把用到 pip install 都改成 pip3 install 再装一次就不会ModuleNotFoundError: No module named 'wda'

**Comment by GitHubZebra** [comment]
运行起来之后，上传分数传不上去啊，老铁们

**Comment by wangwanjie** [comment]
@GitHubZebra 我们都一样
