### ISSUE TITLE
报错 os.remove('autojump.png')

### ISSUE THREAD

**Issue by wpeiguang** [wangshub/wechat_jump_game#762]
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 263, in <module>
    main()
  File "wechat_jump_auto.py", line 235, in main
    check_screenshot()
  File "wechat_jump_auto.py", line 207, in check_screenshot
    check_screenshot()
  File "wechat_jump_auto.py", line 197, in check_screenshot
    os.remove('autojump.png')
WindowsError: [Error 32] : 'autojump.png'

**Comment by fu9852531** [comment]
手机型号？

把开发者选项的安全模式打开
不要只开MTP模式

**Comment by MrLevo520** [comment]
请使用adb免配置版本，或使用最新版release app一键起跳https://github.com/wangshub/wechat_jump_game/releases
下次请规范提交issue，谢谢
