### ISSUE TITLE
command not found??

### ISSUE THREAD

**Issue by Kyooooooo** [wangshub/wechat_jump_game#77]
sh: adb: command not found
sh: adb: command not found
Traceback (most recent call last):
  File "wechat_jump_auto.py", line 139, in <module>
    main()
  File "wechat_jump_auto.py", line 127, in main
    im = Image.open("./1.png")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: './1.png'

**Comment by as00v1** [comment]
Windows环境的话，检查一下adb有没有配到环境变量里。。。
