### ISSUE TITLE
运行脚本时报错invalid syntax

### ISSUE THREAD

**Issue by BlinkG** [wangshub/wechat_jump_game#774]
程序版本号：1.1.1
**********
Screen: Physical size: x
Density: Physical density: x
Override density: x
DeviceType: mi note3
OS: Android+Windows
Python: 3.6.3
**********
遇到问题：运行脚本时报错
Traceback (most recent call last):
  File "C:\Users\Blink_G\Desktop\jump\wechat_jump_auto.py", line 24, in <module>
    from common import debug,config
  File "C:\Users\Blink_G\Desktop\jump\common\__init__.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
改进和建议：无

**Comment by 1204TMax** [comment]
我也是这个问题 你解决了吗
