### ISSUE TITLE
几个改良建议-附修改后代码(可解决夜神模拟器不能跑的问题)

### ISSUE THREAD

**Issue by Erimus-Koo** [wangshub/wechat_jump_game#801]
> 感谢@wangshub。本来想用按键精灵写的，代码不熟，刚好看到这个python的，赞。
> 用安卓模拟器跑的，碰到不少坑。有模拟器的问题，也有adb的问题，也有代码的问题。先聊代码，模拟器问题放到最后。

# 1.截图方向判断
一开始模拟器跑经常跳几下就死了，后来用手动跳，发现原来图是横着的。所以auto里的所有判断都是方向错误状态下做出的！  
发现问题改起来就很方便了，代码如下：
```
def find_piece_and_board(im):
	'''
	寻找关键坐标
	'''
	w, h = im.size
	# ========== 添加图片方向判断 ==========
	if w>h:
		im = im.rotate(-90,expand=True)
		w,h = h,w
	print('image | w:%s | h:%s'%(w,h))
	# ==========
```
在 `find_piece_and_board` 里添加一个方向判断。但是不熟悉adb，所以我的情况是-90，具体还需要加工下。

# 2.跳跃算法简化
现在的跳跃算法是根据直线距离来的，但因为角度固定，于是直线距离和x轴距离是等比的。  
另外现在的跳跃是根据直线距离来计算时间的，但出于游戏制作的角度考虑，很可能UI是根据视窗宽度决定的。  
那么其实可以考虑把跳跃距离变成 **【宽度百分比】**，然后用一个 **【固定系数】** 计算跳跃时间，这样就 **不用config了** 。
> PS: 夜神模拟器找config文件也是错误的，我是1280*720，但调用的是其他的。
```
	# ========== 另一种跳跃算法 ==========
	shortEdge = min(im.size)
	jumpLength = abs(board_x-piece_x)/shortEdge
	coefficient = 1700 #跳跃系数
	press_time = max(int(jumpLength*coefficient),200)
	print('jump:%.2f%% | time: %s'%(jumpLength*100,press_time))
```
按照这个思路，其实config里的数值，都是可以换算的。基本就不用config了。
但这个方法不知道在更宽的，比如4:3的设备上还准不准。  
而且那种设备下，默认的y从1/3到2/3的判断可能也会有问题。

# 3.再玩一局判断
死亡后有蛮大概率点到排行榜，然后无法自动退出，可能swipe的位置可以再搞一下。

---

# 夜神模拟器的几个坑：
* 需要在模拟器多开界面建一个5.1的安卓，默认是4.4.2，会闪退。
* 需要安装adb后，用安装的adb替换夜神模拟器自带的adb.exe和nox_adb.exe。
* 环境配置path用夜神的，`~/nox/bin`

**Comment by Erimus-Koo** [comment]
另外有一个计算坑点是：
* 在连续向右跳的时候，如果没有跳到中心，这时候是有【左下/右上】这个轴上的偏移的。
* 下一次如果还是右跳，这个偏移量其实是需要计算在跳跃距离里的。
* 但如果下一次是左跳，很可能起始点是【右下/左上】轴的中心。
* 比如上一次右跳多了，看似小人在格子右侧，但下一次左跳，很可能是从中心开始计算距离的。
* 但目前的取值法是无法抵消这个偏移量的。
* 我也没有好的办法，就是描述现象。摊手。

**Comment by Erimus-Koo** [comment]
@MrLevo520 @binderclip 
又整了一下主代码，发现如果按照第2点忽略Y值，很多y坐标判断都可以省略了，可以简化非常多。

**Comment by Erimus-Koo** [comment]
# 精简后
精简了一下代码，重写了几个参数。
  
- 寻找棋子部分优化，先粗查后精查，稍微减少点计算。
- 棋子颜色范围放大了一些。
- 棋子和落点的宽度高度等参数，都根据窄边自动计算，抛弃config。

在夜神模拟器下，720*1280运行正常。其他机型有兴趣可以测试一下。

```
# coding: utf-8
'''
# === 思路 ===
# 核心：每次落稳之后截图，根据截图算出棋子的坐标和下一个块顶面的中点坐标，
#      根据两个点的距离乘以一个时间系数获得长按的时间
# 识别棋子：靠棋子的颜色来识别位置，通过截图发现最下面一行大概是一条直线，就从上往下一行一行遍历，
#      比较颜色（颜色用了一个区间来比较）找到最下面的那一行的所有点，然后求个中点，
#      求好之后再让 Y 轴坐标减小棋子底盘的一半高度从而得到中心点的坐标
# 识别棋盘：靠底色和方块的色差来做，从分数之下的位置开始，一行一行扫描，由于圆形的块最顶上是一条线，
#      方形的上面大概是一个点，所以就用类似识别棋子的做法多识别了几个点求中点，
#      这时候得到了块中点的 X 轴坐标，这时候假设现在棋子在当前块的中心，
#      根据一个通过截图获取的固定的角度来推出中点的 Y 坐标
# 最后：根据两点的坐标算距离乘以系数来获取长按时间（似乎可以直接用 X 轴距离）
'''
import os
import sys
import subprocess
import time
import math
from PIL import Image
import random
from six.moves import input

VERSION = "1.1.1"


# ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆


screenshot_way = 2

def check_screenshot():
	'''
	检查获取截图的方式
	'''
	global screenshot_way
	if os.path.isfile('autojump.png'):
		os.remove('autojump.png')
	if (screenshot_way < 0):
		print('暂不支持当前设备')
		sys.exit()
	pull_screenshot()
	try:
		Image.open('./autojump.png').load()
		print('Capture Method: {}'.format(screenshot_way))
	except Exception:
		screenshot_way -= 1
		check_screenshot()

def pull_screenshot():
	'''
	新的方法请根据效率及适用性由高到低排序
	'''
	global screenshot_way
	if screenshot_way == 2 or screenshot_way == 1:
		process = subprocess.Popen('adb shell screencap -p', shell=True, stdout=subprocess.PIPE)
		screenshot = process.stdout.read()
		if screenshot_way == 2:
			binary_screenshot = screenshot.replace(b'\r\n', b'\n')
		else:
			binary_screenshot = screenshot.replace(b'\r\r\n', b'\n')
		f = open('autojump.png', 'wb')
		f.write(binary_screenshot)
		f.close()
	elif screenshot_way == 0:
		os.system('adb shell screencap -p /sdcard/autojump.png')
		os.system('adb pull /sdcard/autojump.png .')


# ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆


def set_button_position(im):
	'''
	将 swipe 设置为 `再来一局` 按钮的位置
	'''
	global swipe_x1, swipe_y1, swipe_x2, swipe_y2
	w, h = im.size
	left = int(w / 2)
	top = int(1584 * (h / 1920.0))
	left = int(random.uniform(left-50, left+50))
	top = int(random.uniform(top-10, top+10))    # 随机防 ban
	swipe_x1, swipe_y1, swipe_x2, swipe_y2 = left, top, left, top


# ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆


def find_piece_and_board(im):
	'''
	寻找关键坐标
	'''
	w, h = im.size #图片宽高
	im_pixel = im.load()


	scan_start_y = 0  # 扫描的起始 y 坐标
	# 以 50px 步长，尝试探测 scan_start_y
	for i in range((h-w)//2, h, 50):
		last_pixel = im_pixel[0, i]
		for j in range(1, w, 10):
			pixel = im_pixel[j, i]
			# 不是纯色的线，则记录 scan_start_y 的值，准备跳出循环
			if pixel[0] != last_pixel[0] or pixel[1] != last_pixel[1] or pixel[2] != last_pixel[2]:
				scan_start_y = i - 50
				break
		if scan_start_y:
			break
	print('scan_start_y: {}'.format(scan_start_y))

	def find_piece(pixel):
		return (50 < pixel[0] < 70) and (50 < pixel[1] < 70) and (90 < pixel[2] < 110)

	# 寻找棋子 ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆
	piece_base_height_1_2 = w//50

	# 粗查棋子位置
	piece_found,piece_tx,piece_ty = 0,0,0
	scan_piece_unit = w//40
	ny = (h+w)//2 #寻找下限 从画面中央的正方形的下缘开始
	while ny>scan_start_y and not piece_found:
		ny -= scan_piece_unit
		for nx in range(0,w,scan_piece_unit):
			pixel = im_pixel[nx,ny]
			if find_piece(pixel):
				piece_tx,piece_ty = nx,ny
				piece_found = True
				break
	print('piece_tx:%s | piece_ty:%s'%(piece_tx,piece_ty))
	if not all((piece_tx,piece_ty)): return 0, 0, 0, 0 #没找到棋子

	# 精查棋子位置
	piece_x,piece_y = 0,0
	piece_x_set = set()
	piece_width = w//14
	piece_height = w//5
	for ny in range(piece_ty+scan_piece_unit,piece_ty-piece_height,-1):
		for nx in range(max(piece_tx-piece_width,0),min(piece_tx+piece_width,w)):
			pixel = im_pixel[nx,ny]
			# print(nx,ny,pixel)
			if find_piece(pixel):
				piece_x_set.add(nx)
				piece_y = ny-piece_base_height_1_2 #上移棋子底盘高度的一半
		if piece_x_set:
			print(piece_x_set)
			piece_x = int(sum(piece_x_set)/len(piece_x_set))
			break
	print('piece_x:%s | piece_y:%s'%(piece_x,piece_y))


	# 寻找落点 ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆
	board_x,board_y = 0,0
	# 限制棋盘扫描的横坐标，避免音符 bug
	if piece_x < w/2:
		board_x_start,board_x_end = piece_x,w
	else:
		board_x_start,board_x_end = 0,piece_x

	# 寻找落点顶点
	for by in range((h-w)//2,(h+w)//2,2):
		bg_pixel = im_pixel[0, by]
		if board_x or board_y: break #找到了退出
		board_x_set = set()

		for bx in range(board_x_start, board_x_end):
			pixel = im_pixel[bx, by]
			# 修掉脑袋比下一个小格子还高的情况的 bug
			if abs(bx - piece_x) < piece_width*1.5: continue

			# 修掉圆顶的时候一条线导致的小 bug，这个颜色判断应该 OK，暂时不提出来
			if abs(pixel[0] - bg_pixel[0]) + abs(pixel[1] - bg_pixel[1]) + abs(pixel[2] - bg_pixel[2]) > 10:
				board_x_set.add(bx)
		if board_x_set:
			board_x = int(sum(board_x_set)/len(board_x_set))
	board_pixel = im_pixel[board_x, by]

	# 使用方法2 不用计算y点 所以以下部分可以省略

	# 从上顶点往下 +274 的位置开始向上找颜色与上顶点一样的点，为下顶点
	# 该方法对所有纯色平面和部分非纯色平面有效，对高尔夫草坪面、木纹桌面、药瓶和非菱形的碟机（好像是）会判断错误
	# board_max_height = int(w/2/120*70) #菱形宽高比为120:70
	# by2 = by #by2平台最下缘
	# for by2 in range(i+board_max_height, ny, -1): # 274 取开局时最大的方块的上下顶点距离
	# 	pixel = im_pixel[board_x, by2]
	# 	if abs(pixel[0] - board_pixel[0]) + abs(pixel[1] - board_pixel[1]) + abs(pixel[2] - board_pixel[2]) < 10:
	# 		break
	# board_y = (ny+by2)//2

	# 如果上一跳命中中间，则下个目标中心会出现 r245 g245 b245 的点，利用这个属性弥补上一段代码可能存在的判断错误
	# 若上一跳由于某种原因没有跳到正中间，而下一跳恰好有无法正确识别花纹，则有可能游戏失败，由于花纹面积通常比较大，失败概率较低
	# ty = 0 #target_y
	# for ty in range(ny, ny+board_max_height):
	# 	pixel = im_pixel[board_x, ty]
	# 	if abs(pixel[0] - 245) + abs(pixel[1] - 245) + abs(pixel[2] - 245) == 0:
	# 		board_y = ty+10
	# 		break

	# if not all((board_x, board_y)): return 0, 0, 0, 0

	return piece_x, piece_y, board_x, board_y



def jump(piece_x, piece_y, board_x, board_y,im):
	'''
	跳跃一定的距离
	'''
	# press_coefficient = 2.05
	# distance = math.sqrt((board_x - piece_x) ** 2 + (board_y - piece_y) ** 2)
	# press_time = distance * press_coefficient
	# press_time = max(press_time, 200)   # 设置 200ms 是最小的按压时间
	# press_time = int(press_time)
	# print('distance:%s | time: %s'%(distance,press_time))

	# ========== 只判断x位移的跳跃算法 ==========
	distance2 = abs(board_x-piece_x)
	shortEdge = min(im.size)
	jumpLength = distance2/shortEdge
	press_coefficient = 1700 #720屏原系数为2多一点点 也就是距离为720需要1440ms 所以系数高一点点
	press_time = int(jumpLength*press_coefficient)
	print('jump:%.2f%% | time: %s'%(jumpLength*100,press_time))

	cmd = 'adb shell input swipe {x1} {y1} {x2} {y2} {duration}'.format(
		x1=swipe_x1,
		y1=swipe_y1,
		x2=swipe_x2,
		y2=swipe_y2,
		duration=press_time
	)
	print(cmd)
	os.system(cmd)
	return press_time


# ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆


def main():
	check_screenshot() #检查截图

	count = 0
	i, next_rest, next_rest_time = 0, 1, 1
	while True:
		count += 1
		print('---\n%s | times: %s'%(int(time.time()),count))

		# 获取截图
		pull_screenshot()
		im = Image.open('./autojump.png')
		w,h = im.size
		if w>h: #添加图片方向判断
			im = im.rotate(-90,expand=True)
		# print('image | w:%s | h:%s'%(w,h))

		# 获取棋子和 board 的位置
		piece_x, piece_y, board_x, board_y = find_piece_and_board(im)
		print(piece_x, piece_y, board_x, board_y)
		set_button_position(im) #随机点击位置
		jump(piece_x, piece_y, board_x, board_y,im)

		i += 1
		if i == next_rest:
			print('Jumped {} time，wait {}s'.format(i, next_rest_time))
			time.sleep(next_rest_time)
			print('\nContinue!')
			i, next_rest, next_rest_time = 0, random.randrange(10, 20), random.randrange(5, 10)
		time.sleep(random.uniform(1, 1.5)) #wait for jump finish


# ◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆◆


if __name__ == '__main__':
	main()
```

**Comment by MarvinXu** [comment]
厉害啊，用了您的代码终于不会在第一步就死翘翘了~ 
不过运行到第10步的时候报错了- -
Times:       10 (1515779086)
Traceback (most recent call last):
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\ImageFile.py", line 214, in load
    s = read(self.decodermaxblock)
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\PngImagePlugin.py", line 593, in load_read
    cid, pos, length = self.png.read()
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\PngImagePlugin.py", line 113, in read
    length = i32(s)
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\_binary.py", line 76, in i32be
    return unpack(">I", c[o:o+4])[0]
struct.error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jump_issue_801.py", line 190, in <module>
    main()
  File "jump_issue_801.py", line 170, in main
    im = im.rotate(-90,expand=True)
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\Image.py", line 1785, in rotate
    return self.transpose(ROTATE_270)
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\Image.py", line 2189, in transpose
    self.load()
  File "C:\Users\MarvinXu\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\ImageFile.py", line 219, in load
    raise IOError("image file is truncated")
OSError: image file is truncated

**Comment by MarvinXu** [comment]
![autojump](https://user-images.githubusercontent.com/7382357/34888787-8830d1a6-f806-11e7-9996-a15e8aae8bca.png)
手动跳了几步重新启动，正常。发现在某些情况下截图有问题，导致程序中断，还没找到原因

**Comment by Erimus-Koo** [comment]
去我页面拿最新版
Erimus

**Comment by MarvinXu** [comment]
@Erimus-Koo 我试过了，还是会停。应该是截图出错了，跟这段代码没关系吧

**Comment by Erimus-Koo** [comment]
你把我页面最新代码，最后面的截图标注部分取消注释，看看截图有没有问题。

或者搜搜看最后那句报错，我没碰到过。
