### ISSUE TITLE
报错，求教

### ISSUE THREAD

**Issue by lovesugarxyz** [wangshub/wechat_jump_game#836]
C:\Users\loves\Desktop\we>python wechat_jump_auto_ai.py
Traceback (most recent call last):
  File "wechat_jump_auto_ai.py", line 26, in <module>
    from common import debug, config, ai
  File "C:\Users\loves\Desktop\we\common\debug.py", line 10, in <module>
    from common import ai
  File "C:\Users\loves\Desktop\we\common\ai.py", line 9, in <module>
    from sklearn.linear_model import LinearRegression
  File "C:\Program Files\Python36\lib\site-packages\sklearn\__init__.py", line 134, in <module>
    from .base import clone
  File "C:\Program Files\Python36\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "C:\Program Files\Python36\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\Program Files\Python36\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "C:\Program Files\Python36\lib\site-packages\sklearn\utils\fixes.py", line 144, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr  # noqa
  File "C:\Program Files\Python36\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .isolve import *
  File "C:\Program Files\Python36\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\Program Files\Python36\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: 找不到指定的模块。

**Comment by MrLevo520** [comment]
ai模块还未完全测试，请等待更新
