### ISSUE TITLE
iOS 运行 Python 报错

### ISSUE THREAD

**Issue by Kejiasir** [wangshub/wechat_jump_game#885]
命令行运行 `python3 wechat_jump_iOS_py3.py` 和 `python3 wechat_jump_auto_iOS.py` 皆报错哇~

retry to connect, error: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d16eb8>: Failed to establish a new connection: [Errno 61] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x103d16eb8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d16eb8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 70, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d16eb8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x103d2b6a0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d2b6a0>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 53, in <module>
    s = c.session()
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 75, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103d2b6a0>: Failed to establish a new connection: [Errno 61] Connection refused',))

********** 
Python:  `3.6`
Device:  `iPhone 6s`
OS:  `10.13.2`
iOS: `11.2.1`
********** 

依赖和 OSX 的 wda 都已经安装了
```
➜  wechat_jump_game git:(master) ✗ pip3.6 install --pre facebook-wda

Requirement already satisfied: facebook-wda in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python3.6/site-packages (from facebook-wda)
Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from facebook-wda)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.9.1->facebook-wda)

➜  wechat_jump_game git:(master) ✗ pip3.6 install -r requirements.txt 

Requirement already satisfied: backports.functools-lru-cache==1.4 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: cycler==0.10.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: matplotlib==2.1.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: numpy==1.13.3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: olefile==0.44 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: opencv-python==3.4.0.12 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: Pillow==4.3.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: pyparsing==2.2.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: python-dateutil==2.6.1 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: pytz==2017.3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: six==1.11.0 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 11))
```

`WebDriverAgent ` 也运行成功
```
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "11.2.1"
    },
    "ios" : {
      "simulatorVersion" : "11.2.1",
      "ip" : "192.168.1.100"
    },
    "build" : {
      "time" : "Jan  4 2018 08:57:11"
    }
  },
  "sessionId" : "C4CB73DB-7E93-49FC-9B9A-E7435FE468D0",
  "status" : 0
}
```

**Comment by oneofai** [comment]
`status`的 URL 是 `http://IP:8100/status`还是 `http://localhost:8100/status`?

**Comment by Kejiasir** [comment]
@oneofai 这个 http://192.168.1.105:8100/status
```
// xcode 控制台输出
Built at Jan  4 2018 10:09:46
ServerURLHere->http://192.168.1.105:8100<-ServerURLHere
```
刚刚试了下, iPhone 5 也是报同样的错

**Comment by oneofai** [comment]
@Kejiasir 这是你手机的 IP, 你要么做下端口代理, 要么需要在`wechat_jump_iOS_py3.py`或`wechat_jump_auto_iOS.py` 文件的 `c = wda.Client()` 指定你的 IP, 具体见上个回复

**Comment by Kejiasir** [comment]
@oneofai 好的, 我试试看, O(∩_∩)O谢谢

**Comment by Kejiasir** [comment]
@oneofai 我用iproxy 8100 8100把 iPhone 的端口成功转发到 Mac 上了, `http://localhost:8100/status` 已经能成功显示 json 串,  但现在终端运行报错又不一样了
```
Traceback (most recent call last):
  File "wechat_jump_auto_iOS.py", line 199, in <module>
    main()
  File "wechat_jump_auto_iOS.py", line 177, in main
    pull_screenshot()
  File "wechat_jump_auto_iOS.py", line 61, in pull_screenshot
    c.screenshot('1.png')
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/usr/local/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

(
	0   CoreFoundation                      0x21645b23 <redacted> + 150
	1   libobjc.A.dylib                     0x20e02dff objc_exception_throw + 38
	2   CoreFoundation                      0x216459e1 <redacted> + 0
	3   Foundation                          0x21e2c73b <redacted> + 90
	4   XCTest                              0x00236985 -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192
	5   XCTest                              0x00236877 -[XCUIScreen screenshotDataForQuality:rect:error:] + 68
	6   WebDriverAgentLib                   0x0294ac81 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 638
	7   WebDriverAgentLib                   0x0292e3bf +[FBScreenshotCommands handleGetScreenshot:] + 130
	8   WebDriverAgentLib                   0x0293a391 -[FBRoute_TargetAction mountRequest:intoResponse:] + 184
	9   WebDriverAgentLib                   0x029328a3 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 594
	10  RoutingHTTPServer                   0x0309cc7f -[RoutingHTTPServer handleRoute:withRequest:response:] + 94
	11  RoutingHTTPServer                   0x0309d321 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 40
	12  libdispatch.dylib                   0x211e44ab <redacted> + 498
	13  libdispatch.dylib                   0x211d7cab <redacted> + 22
	14  libdispatch.dylib                   0x211dc559 _dispatch_main_queue_callback_4CF + 1532
	15  CoreFoundation                      0x21607755 <redacted> + 8
	16  CoreFoundation                      0x21605c4f <redacted> + 1590
	17  CoreFoundation                      0x215541c9 CFRunLoopRunSpecific + 516
	18  CoreFoundation                      0x21553fbd CFRunLoopRunInMode + 108
	19  Foundation                          0x21da142d <redacted> + 268
	20  WebDriverAgentLib                   0x029317e7 -[FBWebServer startServing] + 492
	21  WebDriverAgentRunner                0x007e9c1b -[UITestingUITests testRunner] + 156
	22  CoreFoundation                      0x2164a664 <redacted> + 68
	23  CoreFoundation                      0x2156f8bd <redacted> + 292
	24  XCTest                              0x002215e5 __24-[XCTestCase invokeTest]_block_invoke.275 + 42
	25  XCTest                              0x00221355 __24-[XCTestCase invokeTest]_block_invoke + 836
	26  XCTest                              0x002653b7 -[XCUITestContext performInScope:] + 306
	27  XCTest                              0x0022100b -[XCTestCase invokeTest] + 144
	28  XCTest                              0x00222107 __26-[XCTestCase performTest:]_block_invoke.382 + 110
	29  XCTest                              0x00269bd9 +[XCTContext runInContextForTestCase:block:] + 244
	30  XCTest                              0x00221b43 -[XCTestCase performTest:] + 618
	31  XCTest                              0x0021dde1 __27-[XCTestSuite performTest:]_block_invoke + 356
	32  XCTest                              0x0021d6e7 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 86
	33  XCTest                              0x0021d97f -[XCTestSuite performTest:] + 290
	34  XCTest                              0x0021dde1 __27-[XCTestSuite performTest:]_block_invoke + 356
	35  XCTest                              0x0021d6e7 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 86
	36  XCTest                              0x0021d97f -[XCTestSuite performTest:] + 290
	37  XCTest                              0x0021dde1 __27-[XCTestSuite performTest:]_block_invoke + 356
	38  XCTest                              0x0021d6e7 -[XCTestSuite _performProtectedSectionForTest:testSection:] + 86
	39  XCTest                              0x0021d97f -[XCTestSuite performTest:] + 290
	40  XCTest                              0x00272ed9 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 38
	41  XCTest                              0x00230acf -[XCTestObservationCenter _observeTestExecutionForBlock:] + 482
	42  XCTest                              0x00272d71 -[XCTTestRunSession runTestsAndReturnError:] + 296
	43  XCTest                              0x0020dadb -[XCTestDriver runTestsAndReturnError:] + 302
	44  XCTest                              0x00268e0d _XCTestMain + 884
	45  CoreFoundation                      0x21607909 <redacted> + 12
	46  CoreFoundation                      0x216073c5 <redacted> + 216
	47  CoreFoundation                      0x21605935 <redacted> + 796
	48  CoreFoundation                      0x215541c9 CFRunLoopRunSpecific + 516
	49  CoreFoundation                      0x21553fbd CFRunLoopRunInMode + 108
	50  GraphicsServices                    0x22b70af9 GSEventRunModal + 160
	51  UIKit                               0x25c8c435 UIApplicationMain + 144
	52  WebDriverAgentRunner-Runner         0x000e7f69 WebDriverAgentRunner-Runner + 32617
	53  libdyld.dylib                       0x21200873 <redacted> + 2
))
``` 
同时 xcode 的控制台也输出错误
```
    t =    21.06s Find the Application "local.pid.318" 0x1651ab30
2018-01-04 10:31:00.012 WebDriverAgentRunner-Runner[597:136440] Enqueue Failure: Application local.pid.318 is not running /Users/arvin/Desktop/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =    21.19s Find the Application "local.pid.318" 0x1651ab30
2018-01-04 10:31:00.021 WebDriverAgentRunner-Runner[597:136440] Enqueue Failure: Application local.pid.318 is not running /Users/arvin/Desktop/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =    21.52s Find the Application "local.pid.318" 0x1651a3d0
2018-01-04 10:31:00.350 WebDriverAgentRunner-Runner[597:136440] Enqueue Failure: Application local.pid.318 is not running /Users/arvin/Desktop/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t =    21.53s Find the Application "local.pid.318" 0x1651a3d0
2018-01-04 10:31:00.360 WebDriverAgentRunner-Runner[597:136440] Enqueue Failure: Application local.pid.318 is not running /Users/arvin/Desktop/WebDriverAgent/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-01-04 10:31:00.368 WebDriverAgentRunner-Runner[597:136440] *** Assertion failure in -[XCUIScreen _screenshotDataForQuality:rect:error:], /Library/Caches/com.apple.xbs/Sources/XCTest_iOS/XCTest-13764/Sources/UITesting/XCUIScreen.m:230
```

**Comment by leon0204** [comment]
@Kejiasir 和我一样的错误，我昨天还可以的，今天和你错误一样的

**Comment by Z-hui** [comment]
卡这一天了 不知道怎么解决

**Comment by leon0204** [comment]
b0c958d 我把代码回滚到这个版本就可以了@Kejiasir

**Comment by Kejiasir** [comment]
@leon0204 😂 😂 这样真的好吗?

**Comment by leon0204** [comment]
@Kejiasir  我现在就是和昨天一样的问题了，是可以运行，但是只能100-200分，发现问题在于，那个蓝色的线定位不准，有空再看下什么问题，

**Comment by nightsnack** [comment]
我设置了iproxy 8100 8100

**Comment by Kejiasir** [comment]
@leon0204 😭 WTF~ 然而, 我这里回退了依然不行...

**Comment by mkblbj** [comment]
Xcode不想吐槽了，，问题太多，重装wdb吧，每次都可以解决

**Comment by Kejiasir** [comment]
@mkblbj 唉, 重装wda还是不行~

**Comment by Kejiasir** [comment]
是不是 wda 不支持 iPhone 5, 系统是 9.3.2, 刚刚用 iPhone 6 测试阔以了, 不过150分就挂了...
