### ISSUE TITLE
pip install -r requirements.txt  报错

### ISSUE THREAD

**Issue by wxevu** [wangshub/wechat_jump_game#955]
G:\Program Files\jump\wechat_jump_game-master>pip install -r requirements.txt
Collecting backports.functools-lru-cache==1.4 (from -r requirements.txt (line 1))
Exception:
Traceback (most recent call last):
  File "g:\program files\python2.7\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "g:\program files\python2.7\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "g:\program files\python2.7\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "g:\program files\python2.7\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "g:\program files\python2.7\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "g:\program files\python2.7\lib\site-packages\pip\download.py", line 659, in unpack_http_url
    hashes)
  File "g:\program files\python2.7\lib\site-packages\pip\download.py", line 880, in _download_http_url
    file_path = os.path.join(temp_dir, filename)
  File "g:\program files\python2.7\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 7: ordinal not in range(128)

不懂。。求助

**Comment by hj7020580** [comment]
编码问题，可以尝试升级python版本为3以上。

**Comment by MrLevo520** [comment]
可以使用release版本，不需要安装环境，一键启动

**Comment by wxevu** [comment]
@MrLevo520 @hj7020580  谢谢  刚刚用了one_step_auto_beta1.exe就可以了
